// @generated by protobuf-ts 2.11.1 with parameter disable_ts_nocheck
// @generated from protobuf file "user/user.proto" (package "wws.user", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { UserService } from "./user";
import type { ListUsersResponse } from "./user";
import type { ListUsersRequest } from "./user";
import type { GetUserRequest } from "./user";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { UserResponse } from "./user";
import type { GetCurrentUserRequest } from "./user";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * User service definition
 *
 * @generated from protobuf service wws.user.UserService
 */
export interface IUserServiceClient {
    /**
     * Get current user profile
     *
     * @generated from protobuf rpc: GetCurrentUser
     */
    getCurrentUser(input: GetCurrentUserRequest, options?: RpcOptions): UnaryCall<GetCurrentUserRequest, UserResponse>;
    /**
     * Get user by ID
     *
     * @generated from protobuf rpc: GetUser
     */
    getUser(input: GetUserRequest, options?: RpcOptions): UnaryCall<GetUserRequest, UserResponse>;
    /**
     * List users in an organization
     *
     * @generated from protobuf rpc: ListUsers
     */
    listUsers(input: ListUsersRequest, options?: RpcOptions): UnaryCall<ListUsersRequest, ListUsersResponse>;
}
/**
 * User service definition
 *
 * @generated from protobuf service wws.user.UserService
 */
export class UserServiceClient implements IUserServiceClient, ServiceInfo {
    typeName = UserService.typeName;
    methods = UserService.methods;
    options = UserService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * Get current user profile
     *
     * @generated from protobuf rpc: GetCurrentUser
     */
    getCurrentUser(input: GetCurrentUserRequest, options?: RpcOptions): UnaryCall<GetCurrentUserRequest, UserResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetCurrentUserRequest, UserResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Get user by ID
     *
     * @generated from protobuf rpc: GetUser
     */
    getUser(input: GetUserRequest, options?: RpcOptions): UnaryCall<GetUserRequest, UserResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetUserRequest, UserResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * List users in an organization
     *
     * @generated from protobuf rpc: ListUsers
     */
    listUsers(input: ListUsersRequest, options?: RpcOptions): UnaryCall<ListUsersRequest, ListUsersResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListUsersRequest, ListUsersResponse>("unary", this._transport, method, opt, input);
    }
}
