// @generated by protobuf-ts 2.11.1 with parameter disable_ts_nocheck
// @generated from protobuf file "organization/organization.proto" (package "wws.organization", syntax proto3)
// tslint:disable
import { Empty } from "../common/common";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { PaginationResponse } from "../common/common";
import { PaginationRequest } from "../common/common";
import { User } from "../user/user";
import { Timestamp } from "../common/common";
/**
 * Organization message
 *
 * @generated from protobuf message wws.organization.Organization
 */
export interface Organization {
    /**
     * @generated from protobuf field: int32 id = 1
     */
    id: number;
    /**
     * @generated from protobuf field: string name = 2
     */
    name: string;
    /**
     * @generated from protobuf field: int32 owner_id = 3
     */
    ownerId: number;
    /**
     * @generated from protobuf field: string description = 4
     */
    description: string;
    /**
     * @generated from protobuf field: string avatar_url = 5
     */
    avatarUrl: string;
    /**
     * @generated from protobuf field: wws.common.Timestamp created_at = 6
     */
    createdAt?: Timestamp;
    /**
     * @generated from protobuf field: wws.common.Timestamp updated_at = 7
     */
    updatedAt?: Timestamp;
}
/**
 * Member message
 *
 * @generated from protobuf message wws.organization.Member
 */
export interface Member {
    /**
     * @generated from protobuf field: int32 id = 1
     */
    id: number;
    /**
     * @generated from protobuf field: wws.user.User user = 2
     */
    user?: User;
    /**
     * @generated from protobuf field: string role = 3
     */
    role: string; // admin, member, viewer
    /**
     * @generated from protobuf field: bool accepted = 4
     */
    accepted: boolean;
    /**
     * @generated from protobuf field: wws.common.Timestamp invited_at = 5
     */
    invitedAt?: Timestamp;
    /**
     * @generated from protobuf field: wws.common.Timestamp joined_at = 6
     */
    joinedAt?: Timestamp;
}
/**
 * Invitation message
 *
 * @generated from protobuf message wws.organization.Invitation
 */
export interface Invitation {
    /**
     * @generated from protobuf field: int32 id = 1
     */
    id: number;
    /**
     * @generated from protobuf field: int32 organization_id = 2
     */
    organizationId: number;
    /**
     * @generated from protobuf field: string email = 3
     */
    email: string;
    /**
     * @generated from protobuf field: string role = 4
     */
    role: string;
    /**
     * @generated from protobuf field: int32 invited_by = 5
     */
    invitedBy: number;
    /**
     * @generated from protobuf field: bool accepted = 6
     */
    accepted: boolean;
    /**
     * @generated from protobuf field: wws.common.Timestamp expires_at = 7
     */
    expiresAt?: Timestamp;
    /**
     * @generated from protobuf field: wws.common.Timestamp created_at = 8
     */
    createdAt?: Timestamp;
}
/**
 * ListOrganizationsRequest
 *
 * @generated from protobuf message wws.organization.ListOrganizationsRequest
 */
export interface ListOrganizationsRequest {
    /**
     * @generated from protobuf field: wws.common.PaginationRequest pagination = 1
     */
    pagination?: PaginationRequest;
}
/**
 * ListOrganizationsResponse
 *
 * @generated from protobuf message wws.organization.ListOrganizationsResponse
 */
export interface ListOrganizationsResponse {
    /**
     * @generated from protobuf field: repeated wws.organization.Organization organizations = 1
     */
    organizations: Organization[];
    /**
     * @generated from protobuf field: wws.common.PaginationResponse pagination = 2
     */
    pagination?: PaginationResponse;
}
/**
 * GetOrganizationRequest
 *
 * @generated from protobuf message wws.organization.GetOrganizationRequest
 */
export interface GetOrganizationRequest {
    /**
     * @generated from protobuf field: int32 id = 1
     */
    id: number;
}
/**
 * OrganizationResponse
 *
 * @generated from protobuf message wws.organization.OrganizationResponse
 */
export interface OrganizationResponse {
    /**
     * @generated from protobuf field: wws.organization.Organization organization = 1
     */
    organization?: Organization;
}
/**
 * CreateOrganizationRequest
 *
 * @generated from protobuf message wws.organization.CreateOrganizationRequest
 */
export interface CreateOrganizationRequest {
    /**
     * @generated from protobuf field: string name = 1
     */
    name: string;
    /**
     * @generated from protobuf field: string description = 2
     */
    description: string;
}
/**
 * UpdateOrganizationRequest
 *
 * @generated from protobuf message wws.organization.UpdateOrganizationRequest
 */
export interface UpdateOrganizationRequest {
    /**
     * @generated from protobuf field: int32 id = 1
     */
    id: number;
    /**
     * @generated from protobuf field: string name = 2
     */
    name: string;
    /**
     * @generated from protobuf field: string description = 3
     */
    description: string;
}
/**
 * DeleteOrganizationRequest
 *
 * @generated from protobuf message wws.organization.DeleteOrganizationRequest
 */
export interface DeleteOrganizationRequest {
    /**
     * @generated from protobuf field: int32 id = 1
     */
    id: number;
}
/**
 * InviteUserRequest
 *
 * @generated from protobuf message wws.organization.InviteUserRequest
 */
export interface InviteUserRequest {
    /**
     * @generated from protobuf field: int32 organization_id = 1
     */
    organizationId: number;
    /**
     * @generated from protobuf field: string email = 2
     */
    email: string;
    /**
     * @generated from protobuf field: string role = 3
     */
    role: string;
}
/**
 * InviteUserResponse
 *
 * @generated from protobuf message wws.organization.InviteUserResponse
 */
export interface InviteUserResponse {
    /**
     * @generated from protobuf field: wws.organization.Invitation invitation = 1
     */
    invitation?: Invitation;
}
/**
 * AcceptInvitationRequest
 *
 * @generated from protobuf message wws.organization.AcceptInvitationRequest
 */
export interface AcceptInvitationRequest {
    /**
     * @generated from protobuf field: int32 invitation_id = 1
     */
    invitationId: number;
}
/**
 * ListMembersRequest
 *
 * @generated from protobuf message wws.organization.ListMembersRequest
 */
export interface ListMembersRequest {
    /**
     * @generated from protobuf field: int32 organization_id = 1
     */
    organizationId: number;
    /**
     * @generated from protobuf field: wws.common.PaginationRequest pagination = 2
     */
    pagination?: PaginationRequest;
}
/**
 * ListMembersResponse
 *
 * @generated from protobuf message wws.organization.ListMembersResponse
 */
export interface ListMembersResponse {
    /**
     * @generated from protobuf field: repeated wws.organization.Member members = 1
     */
    members: Member[];
    /**
     * @generated from protobuf field: wws.common.PaginationResponse pagination = 2
     */
    pagination?: PaginationResponse;
}
/**
 * MemberResponse
 *
 * @generated from protobuf message wws.organization.MemberResponse
 */
export interface MemberResponse {
    /**
     * @generated from protobuf field: wws.organization.Member member = 1
     */
    member?: Member;
}
/**
 * UpdateMemberRoleRequest
 *
 * @generated from protobuf message wws.organization.UpdateMemberRoleRequest
 */
export interface UpdateMemberRoleRequest {
    /**
     * @generated from protobuf field: int32 organization_id = 1
     */
    organizationId: number;
    /**
     * @generated from protobuf field: int32 user_id = 2
     */
    userId: number;
    /**
     * @generated from protobuf field: string role = 3
     */
    role: string;
}
/**
 * RemoveMemberRequest
 *
 * @generated from protobuf message wws.organization.RemoveMemberRequest
 */
export interface RemoveMemberRequest {
    /**
     * @generated from protobuf field: int32 organization_id = 1
     */
    organizationId: number;
    /**
     * @generated from protobuf field: int32 user_id = 2
     */
    userId: number;
}
// @generated message type with reflection information, may provide speed optimized methods
class Organization$Type extends MessageType<Organization> {
    constructor() {
        super("wws.organization.Organization", [
            { no: 1, name: "id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "owner_id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "description", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "avatar_url", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "created_at", kind: "message", T: () => Timestamp },
            { no: 7, name: "updated_at", kind: "message", T: () => Timestamp }
        ]);
    }
    create(value?: PartialMessage<Organization>): Organization {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = 0;
        message.name = "";
        message.ownerId = 0;
        message.description = "";
        message.avatarUrl = "";
        if (value !== undefined)
            reflectionMergePartial<Organization>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Organization): Organization {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 id */ 1:
                    message.id = reader.int32();
                    break;
                case /* string name */ 2:
                    message.name = reader.string();
                    break;
                case /* int32 owner_id */ 3:
                    message.ownerId = reader.int32();
                    break;
                case /* string description */ 4:
                    message.description = reader.string();
                    break;
                case /* string avatar_url */ 5:
                    message.avatarUrl = reader.string();
                    break;
                case /* wws.common.Timestamp created_at */ 6:
                    message.createdAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.createdAt);
                    break;
                case /* wws.common.Timestamp updated_at */ 7:
                    message.updatedAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.updatedAt);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Organization, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 id = 1; */
        if (message.id !== 0)
            writer.tag(1, WireType.Varint).int32(message.id);
        /* string name = 2; */
        if (message.name !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.name);
        /* int32 owner_id = 3; */
        if (message.ownerId !== 0)
            writer.tag(3, WireType.Varint).int32(message.ownerId);
        /* string description = 4; */
        if (message.description !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.description);
        /* string avatar_url = 5; */
        if (message.avatarUrl !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.avatarUrl);
        /* wws.common.Timestamp created_at = 6; */
        if (message.createdAt)
            Timestamp.internalBinaryWrite(message.createdAt, writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        /* wws.common.Timestamp updated_at = 7; */
        if (message.updatedAt)
            Timestamp.internalBinaryWrite(message.updatedAt, writer.tag(7, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wws.organization.Organization
 */
export const Organization = new Organization$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Member$Type extends MessageType<Member> {
    constructor() {
        super("wws.organization.Member", [
            { no: 1, name: "id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "user", kind: "message", T: () => User },
            { no: 3, name: "role", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "accepted", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 5, name: "invited_at", kind: "message", T: () => Timestamp },
            { no: 6, name: "joined_at", kind: "message", T: () => Timestamp }
        ]);
    }
    create(value?: PartialMessage<Member>): Member {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = 0;
        message.role = "";
        message.accepted = false;
        if (value !== undefined)
            reflectionMergePartial<Member>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Member): Member {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 id */ 1:
                    message.id = reader.int32();
                    break;
                case /* wws.user.User user */ 2:
                    message.user = User.internalBinaryRead(reader, reader.uint32(), options, message.user);
                    break;
                case /* string role */ 3:
                    message.role = reader.string();
                    break;
                case /* bool accepted */ 4:
                    message.accepted = reader.bool();
                    break;
                case /* wws.common.Timestamp invited_at */ 5:
                    message.invitedAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.invitedAt);
                    break;
                case /* wws.common.Timestamp joined_at */ 6:
                    message.joinedAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.joinedAt);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Member, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 id = 1; */
        if (message.id !== 0)
            writer.tag(1, WireType.Varint).int32(message.id);
        /* wws.user.User user = 2; */
        if (message.user)
            User.internalBinaryWrite(message.user, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* string role = 3; */
        if (message.role !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.role);
        /* bool accepted = 4; */
        if (message.accepted !== false)
            writer.tag(4, WireType.Varint).bool(message.accepted);
        /* wws.common.Timestamp invited_at = 5; */
        if (message.invitedAt)
            Timestamp.internalBinaryWrite(message.invitedAt, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        /* wws.common.Timestamp joined_at = 6; */
        if (message.joinedAt)
            Timestamp.internalBinaryWrite(message.joinedAt, writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wws.organization.Member
 */
export const Member = new Member$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Invitation$Type extends MessageType<Invitation> {
    constructor() {
        super("wws.organization.Invitation", [
            { no: 1, name: "id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "organization_id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "email", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "role", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "invited_by", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 6, name: "accepted", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 7, name: "expires_at", kind: "message", T: () => Timestamp },
            { no: 8, name: "created_at", kind: "message", T: () => Timestamp }
        ]);
    }
    create(value?: PartialMessage<Invitation>): Invitation {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = 0;
        message.organizationId = 0;
        message.email = "";
        message.role = "";
        message.invitedBy = 0;
        message.accepted = false;
        if (value !== undefined)
            reflectionMergePartial<Invitation>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Invitation): Invitation {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 id */ 1:
                    message.id = reader.int32();
                    break;
                case /* int32 organization_id */ 2:
                    message.organizationId = reader.int32();
                    break;
                case /* string email */ 3:
                    message.email = reader.string();
                    break;
                case /* string role */ 4:
                    message.role = reader.string();
                    break;
                case /* int32 invited_by */ 5:
                    message.invitedBy = reader.int32();
                    break;
                case /* bool accepted */ 6:
                    message.accepted = reader.bool();
                    break;
                case /* wws.common.Timestamp expires_at */ 7:
                    message.expiresAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.expiresAt);
                    break;
                case /* wws.common.Timestamp created_at */ 8:
                    message.createdAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.createdAt);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Invitation, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 id = 1; */
        if (message.id !== 0)
            writer.tag(1, WireType.Varint).int32(message.id);
        /* int32 organization_id = 2; */
        if (message.organizationId !== 0)
            writer.tag(2, WireType.Varint).int32(message.organizationId);
        /* string email = 3; */
        if (message.email !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.email);
        /* string role = 4; */
        if (message.role !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.role);
        /* int32 invited_by = 5; */
        if (message.invitedBy !== 0)
            writer.tag(5, WireType.Varint).int32(message.invitedBy);
        /* bool accepted = 6; */
        if (message.accepted !== false)
            writer.tag(6, WireType.Varint).bool(message.accepted);
        /* wws.common.Timestamp expires_at = 7; */
        if (message.expiresAt)
            Timestamp.internalBinaryWrite(message.expiresAt, writer.tag(7, WireType.LengthDelimited).fork(), options).join();
        /* wws.common.Timestamp created_at = 8; */
        if (message.createdAt)
            Timestamp.internalBinaryWrite(message.createdAt, writer.tag(8, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wws.organization.Invitation
 */
export const Invitation = new Invitation$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListOrganizationsRequest$Type extends MessageType<ListOrganizationsRequest> {
    constructor() {
        super("wws.organization.ListOrganizationsRequest", [
            { no: 1, name: "pagination", kind: "message", T: () => PaginationRequest }
        ]);
    }
    create(value?: PartialMessage<ListOrganizationsRequest>): ListOrganizationsRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<ListOrganizationsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListOrganizationsRequest): ListOrganizationsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* wws.common.PaginationRequest pagination */ 1:
                    message.pagination = PaginationRequest.internalBinaryRead(reader, reader.uint32(), options, message.pagination);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListOrganizationsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* wws.common.PaginationRequest pagination = 1; */
        if (message.pagination)
            PaginationRequest.internalBinaryWrite(message.pagination, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wws.organization.ListOrganizationsRequest
 */
export const ListOrganizationsRequest = new ListOrganizationsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListOrganizationsResponse$Type extends MessageType<ListOrganizationsResponse> {
    constructor() {
        super("wws.organization.ListOrganizationsResponse", [
            { no: 1, name: "organizations", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Organization },
            { no: 2, name: "pagination", kind: "message", T: () => PaginationResponse }
        ]);
    }
    create(value?: PartialMessage<ListOrganizationsResponse>): ListOrganizationsResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.organizations = [];
        if (value !== undefined)
            reflectionMergePartial<ListOrganizationsResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListOrganizationsResponse): ListOrganizationsResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated wws.organization.Organization organizations */ 1:
                    message.organizations.push(Organization.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* wws.common.PaginationResponse pagination */ 2:
                    message.pagination = PaginationResponse.internalBinaryRead(reader, reader.uint32(), options, message.pagination);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListOrganizationsResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated wws.organization.Organization organizations = 1; */
        for (let i = 0; i < message.organizations.length; i++)
            Organization.internalBinaryWrite(message.organizations[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* wws.common.PaginationResponse pagination = 2; */
        if (message.pagination)
            PaginationResponse.internalBinaryWrite(message.pagination, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wws.organization.ListOrganizationsResponse
 */
export const ListOrganizationsResponse = new ListOrganizationsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetOrganizationRequest$Type extends MessageType<GetOrganizationRequest> {
    constructor() {
        super("wws.organization.GetOrganizationRequest", [
            { no: 1, name: "id", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<GetOrganizationRequest>): GetOrganizationRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = 0;
        if (value !== undefined)
            reflectionMergePartial<GetOrganizationRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetOrganizationRequest): GetOrganizationRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 id */ 1:
                    message.id = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetOrganizationRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 id = 1; */
        if (message.id !== 0)
            writer.tag(1, WireType.Varint).int32(message.id);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wws.organization.GetOrganizationRequest
 */
export const GetOrganizationRequest = new GetOrganizationRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class OrganizationResponse$Type extends MessageType<OrganizationResponse> {
    constructor() {
        super("wws.organization.OrganizationResponse", [
            { no: 1, name: "organization", kind: "message", T: () => Organization }
        ]);
    }
    create(value?: PartialMessage<OrganizationResponse>): OrganizationResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<OrganizationResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: OrganizationResponse): OrganizationResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* wws.organization.Organization organization */ 1:
                    message.organization = Organization.internalBinaryRead(reader, reader.uint32(), options, message.organization);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: OrganizationResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* wws.organization.Organization organization = 1; */
        if (message.organization)
            Organization.internalBinaryWrite(message.organization, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wws.organization.OrganizationResponse
 */
export const OrganizationResponse = new OrganizationResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CreateOrganizationRequest$Type extends MessageType<CreateOrganizationRequest> {
    constructor() {
        super("wws.organization.CreateOrganizationRequest", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "description", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<CreateOrganizationRequest>): CreateOrganizationRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.name = "";
        message.description = "";
        if (value !== undefined)
            reflectionMergePartial<CreateOrganizationRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreateOrganizationRequest): CreateOrganizationRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string name */ 1:
                    message.name = reader.string();
                    break;
                case /* string description */ 2:
                    message.description = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CreateOrganizationRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string name = 1; */
        if (message.name !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.name);
        /* string description = 2; */
        if (message.description !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.description);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wws.organization.CreateOrganizationRequest
 */
export const CreateOrganizationRequest = new CreateOrganizationRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdateOrganizationRequest$Type extends MessageType<UpdateOrganizationRequest> {
    constructor() {
        super("wws.organization.UpdateOrganizationRequest", [
            { no: 1, name: "id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "description", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<UpdateOrganizationRequest>): UpdateOrganizationRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = 0;
        message.name = "";
        message.description = "";
        if (value !== undefined)
            reflectionMergePartial<UpdateOrganizationRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UpdateOrganizationRequest): UpdateOrganizationRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 id */ 1:
                    message.id = reader.int32();
                    break;
                case /* string name */ 2:
                    message.name = reader.string();
                    break;
                case /* string description */ 3:
                    message.description = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UpdateOrganizationRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 id = 1; */
        if (message.id !== 0)
            writer.tag(1, WireType.Varint).int32(message.id);
        /* string name = 2; */
        if (message.name !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.name);
        /* string description = 3; */
        if (message.description !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.description);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wws.organization.UpdateOrganizationRequest
 */
export const UpdateOrganizationRequest = new UpdateOrganizationRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeleteOrganizationRequest$Type extends MessageType<DeleteOrganizationRequest> {
    constructor() {
        super("wws.organization.DeleteOrganizationRequest", [
            { no: 1, name: "id", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<DeleteOrganizationRequest>): DeleteOrganizationRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = 0;
        if (value !== undefined)
            reflectionMergePartial<DeleteOrganizationRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DeleteOrganizationRequest): DeleteOrganizationRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 id */ 1:
                    message.id = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DeleteOrganizationRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 id = 1; */
        if (message.id !== 0)
            writer.tag(1, WireType.Varint).int32(message.id);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wws.organization.DeleteOrganizationRequest
 */
export const DeleteOrganizationRequest = new DeleteOrganizationRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class InviteUserRequest$Type extends MessageType<InviteUserRequest> {
    constructor() {
        super("wws.organization.InviteUserRequest", [
            { no: 1, name: "organization_id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "email", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "role", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<InviteUserRequest>): InviteUserRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.organizationId = 0;
        message.email = "";
        message.role = "";
        if (value !== undefined)
            reflectionMergePartial<InviteUserRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: InviteUserRequest): InviteUserRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 organization_id */ 1:
                    message.organizationId = reader.int32();
                    break;
                case /* string email */ 2:
                    message.email = reader.string();
                    break;
                case /* string role */ 3:
                    message.role = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: InviteUserRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 organization_id = 1; */
        if (message.organizationId !== 0)
            writer.tag(1, WireType.Varint).int32(message.organizationId);
        /* string email = 2; */
        if (message.email !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.email);
        /* string role = 3; */
        if (message.role !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.role);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wws.organization.InviteUserRequest
 */
export const InviteUserRequest = new InviteUserRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class InviteUserResponse$Type extends MessageType<InviteUserResponse> {
    constructor() {
        super("wws.organization.InviteUserResponse", [
            { no: 1, name: "invitation", kind: "message", T: () => Invitation }
        ]);
    }
    create(value?: PartialMessage<InviteUserResponse>): InviteUserResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<InviteUserResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: InviteUserResponse): InviteUserResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* wws.organization.Invitation invitation */ 1:
                    message.invitation = Invitation.internalBinaryRead(reader, reader.uint32(), options, message.invitation);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: InviteUserResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* wws.organization.Invitation invitation = 1; */
        if (message.invitation)
            Invitation.internalBinaryWrite(message.invitation, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wws.organization.InviteUserResponse
 */
export const InviteUserResponse = new InviteUserResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AcceptInvitationRequest$Type extends MessageType<AcceptInvitationRequest> {
    constructor() {
        super("wws.organization.AcceptInvitationRequest", [
            { no: 1, name: "invitation_id", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<AcceptInvitationRequest>): AcceptInvitationRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.invitationId = 0;
        if (value !== undefined)
            reflectionMergePartial<AcceptInvitationRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AcceptInvitationRequest): AcceptInvitationRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 invitation_id */ 1:
                    message.invitationId = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AcceptInvitationRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 invitation_id = 1; */
        if (message.invitationId !== 0)
            writer.tag(1, WireType.Varint).int32(message.invitationId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wws.organization.AcceptInvitationRequest
 */
export const AcceptInvitationRequest = new AcceptInvitationRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListMembersRequest$Type extends MessageType<ListMembersRequest> {
    constructor() {
        super("wws.organization.ListMembersRequest", [
            { no: 1, name: "organization_id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "pagination", kind: "message", T: () => PaginationRequest }
        ]);
    }
    create(value?: PartialMessage<ListMembersRequest>): ListMembersRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.organizationId = 0;
        if (value !== undefined)
            reflectionMergePartial<ListMembersRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListMembersRequest): ListMembersRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 organization_id */ 1:
                    message.organizationId = reader.int32();
                    break;
                case /* wws.common.PaginationRequest pagination */ 2:
                    message.pagination = PaginationRequest.internalBinaryRead(reader, reader.uint32(), options, message.pagination);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListMembersRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 organization_id = 1; */
        if (message.organizationId !== 0)
            writer.tag(1, WireType.Varint).int32(message.organizationId);
        /* wws.common.PaginationRequest pagination = 2; */
        if (message.pagination)
            PaginationRequest.internalBinaryWrite(message.pagination, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wws.organization.ListMembersRequest
 */
export const ListMembersRequest = new ListMembersRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListMembersResponse$Type extends MessageType<ListMembersResponse> {
    constructor() {
        super("wws.organization.ListMembersResponse", [
            { no: 1, name: "members", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Member },
            { no: 2, name: "pagination", kind: "message", T: () => PaginationResponse }
        ]);
    }
    create(value?: PartialMessage<ListMembersResponse>): ListMembersResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.members = [];
        if (value !== undefined)
            reflectionMergePartial<ListMembersResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListMembersResponse): ListMembersResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated wws.organization.Member members */ 1:
                    message.members.push(Member.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* wws.common.PaginationResponse pagination */ 2:
                    message.pagination = PaginationResponse.internalBinaryRead(reader, reader.uint32(), options, message.pagination);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListMembersResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated wws.organization.Member members = 1; */
        for (let i = 0; i < message.members.length; i++)
            Member.internalBinaryWrite(message.members[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* wws.common.PaginationResponse pagination = 2; */
        if (message.pagination)
            PaginationResponse.internalBinaryWrite(message.pagination, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wws.organization.ListMembersResponse
 */
export const ListMembersResponse = new ListMembersResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class MemberResponse$Type extends MessageType<MemberResponse> {
    constructor() {
        super("wws.organization.MemberResponse", [
            { no: 1, name: "member", kind: "message", T: () => Member }
        ]);
    }
    create(value?: PartialMessage<MemberResponse>): MemberResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<MemberResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: MemberResponse): MemberResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* wws.organization.Member member */ 1:
                    message.member = Member.internalBinaryRead(reader, reader.uint32(), options, message.member);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: MemberResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* wws.organization.Member member = 1; */
        if (message.member)
            Member.internalBinaryWrite(message.member, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wws.organization.MemberResponse
 */
export const MemberResponse = new MemberResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdateMemberRoleRequest$Type extends MessageType<UpdateMemberRoleRequest> {
    constructor() {
        super("wws.organization.UpdateMemberRoleRequest", [
            { no: 1, name: "organization_id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "user_id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "role", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<UpdateMemberRoleRequest>): UpdateMemberRoleRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.organizationId = 0;
        message.userId = 0;
        message.role = "";
        if (value !== undefined)
            reflectionMergePartial<UpdateMemberRoleRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UpdateMemberRoleRequest): UpdateMemberRoleRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 organization_id */ 1:
                    message.organizationId = reader.int32();
                    break;
                case /* int32 user_id */ 2:
                    message.userId = reader.int32();
                    break;
                case /* string role */ 3:
                    message.role = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UpdateMemberRoleRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 organization_id = 1; */
        if (message.organizationId !== 0)
            writer.tag(1, WireType.Varint).int32(message.organizationId);
        /* int32 user_id = 2; */
        if (message.userId !== 0)
            writer.tag(2, WireType.Varint).int32(message.userId);
        /* string role = 3; */
        if (message.role !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.role);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wws.organization.UpdateMemberRoleRequest
 */
export const UpdateMemberRoleRequest = new UpdateMemberRoleRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RemoveMemberRequest$Type extends MessageType<RemoveMemberRequest> {
    constructor() {
        super("wws.organization.RemoveMemberRequest", [
            { no: 1, name: "organization_id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "user_id", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<RemoveMemberRequest>): RemoveMemberRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.organizationId = 0;
        message.userId = 0;
        if (value !== undefined)
            reflectionMergePartial<RemoveMemberRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RemoveMemberRequest): RemoveMemberRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 organization_id */ 1:
                    message.organizationId = reader.int32();
                    break;
                case /* int32 user_id */ 2:
                    message.userId = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RemoveMemberRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 organization_id = 1; */
        if (message.organizationId !== 0)
            writer.tag(1, WireType.Varint).int32(message.organizationId);
        /* int32 user_id = 2; */
        if (message.userId !== 0)
            writer.tag(2, WireType.Varint).int32(message.userId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wws.organization.RemoveMemberRequest
 */
export const RemoveMemberRequest = new RemoveMemberRequest$Type();
/**
 * @generated ServiceType for protobuf service wws.organization.OrganizationService
 */
export const OrganizationService = new ServiceType("wws.organization.OrganizationService", [
    { name: "ListOrganizations", options: {}, I: ListOrganizationsRequest, O: ListOrganizationsResponse },
    { name: "GetOrganization", options: {}, I: GetOrganizationRequest, O: OrganizationResponse },
    { name: "CreateOrganization", options: {}, I: CreateOrganizationRequest, O: OrganizationResponse },
    { name: "UpdateOrganization", options: {}, I: UpdateOrganizationRequest, O: OrganizationResponse },
    { name: "DeleteOrganization", options: {}, I: DeleteOrganizationRequest, O: Empty },
    { name: "InviteUser", options: {}, I: InviteUserRequest, O: InviteUserResponse },
    { name: "AcceptInvitation", options: {}, I: AcceptInvitationRequest, O: Empty },
    { name: "ListMembers", options: {}, I: ListMembersRequest, O: ListMembersResponse },
    { name: "UpdateMemberRole", options: {}, I: UpdateMemberRoleRequest, O: MemberResponse },
    { name: "RemoveMember", options: {}, I: RemoveMemberRequest, O: Empty }
]);
