// @generated by protobuf-ts 2.11.1 with parameter disable_ts_nocheck
// @generated from protobuf file "organization/organization.proto" (package "wws.organization", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { OrganizationService } from "./organization";
import type { RemoveMemberRequest } from "./organization";
import type { MemberResponse } from "./organization";
import type { UpdateMemberRoleRequest } from "./organization";
import type { ListMembersResponse } from "./organization";
import type { ListMembersRequest } from "./organization";
import type { AcceptInvitationRequest } from "./organization";
import type { InviteUserResponse } from "./organization";
import type { InviteUserRequest } from "./organization";
import type { Empty } from "../common/common";
import type { DeleteOrganizationRequest } from "./organization";
import type { UpdateOrganizationRequest } from "./organization";
import type { CreateOrganizationRequest } from "./organization";
import type { OrganizationResponse } from "./organization";
import type { GetOrganizationRequest } from "./organization";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { ListOrganizationsResponse } from "./organization";
import type { ListOrganizationsRequest } from "./organization";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * Organization service definition
 *
 * @generated from protobuf service wws.organization.OrganizationService
 */
export interface IOrganizationServiceClient {
    /**
     * List all organizations
     *
     * @generated from protobuf rpc: ListOrganizations
     */
    listOrganizations(input: ListOrganizationsRequest, options?: RpcOptions): UnaryCall<ListOrganizationsRequest, ListOrganizationsResponse>;
    /**
     * Get organization by ID
     *
     * @generated from protobuf rpc: GetOrganization
     */
    getOrganization(input: GetOrganizationRequest, options?: RpcOptions): UnaryCall<GetOrganizationRequest, OrganizationResponse>;
    /**
     * Create organization
     *
     * @generated from protobuf rpc: CreateOrganization
     */
    createOrganization(input: CreateOrganizationRequest, options?: RpcOptions): UnaryCall<CreateOrganizationRequest, OrganizationResponse>;
    /**
     * Update organization
     *
     * @generated from protobuf rpc: UpdateOrganization
     */
    updateOrganization(input: UpdateOrganizationRequest, options?: RpcOptions): UnaryCall<UpdateOrganizationRequest, OrganizationResponse>;
    /**
     * Delete organization
     *
     * @generated from protobuf rpc: DeleteOrganization
     */
    deleteOrganization(input: DeleteOrganizationRequest, options?: RpcOptions): UnaryCall<DeleteOrganizationRequest, Empty>;
    /**
     * Invite user to organization
     *
     * @generated from protobuf rpc: InviteUser
     */
    inviteUser(input: InviteUserRequest, options?: RpcOptions): UnaryCall<InviteUserRequest, InviteUserResponse>;
    /**
     * Accept invitation
     *
     * @generated from protobuf rpc: AcceptInvitation
     */
    acceptInvitation(input: AcceptInvitationRequest, options?: RpcOptions): UnaryCall<AcceptInvitationRequest, Empty>;
    /**
     * List organization members
     *
     * @generated from protobuf rpc: ListMembers
     */
    listMembers(input: ListMembersRequest, options?: RpcOptions): UnaryCall<ListMembersRequest, ListMembersResponse>;
    /**
     * Update member role
     *
     * @generated from protobuf rpc: UpdateMemberRole
     */
    updateMemberRole(input: UpdateMemberRoleRequest, options?: RpcOptions): UnaryCall<UpdateMemberRoleRequest, MemberResponse>;
    /**
     * Remove member from organization
     *
     * @generated from protobuf rpc: RemoveMember
     */
    removeMember(input: RemoveMemberRequest, options?: RpcOptions): UnaryCall<RemoveMemberRequest, Empty>;
}
/**
 * Organization service definition
 *
 * @generated from protobuf service wws.organization.OrganizationService
 */
export class OrganizationServiceClient implements IOrganizationServiceClient, ServiceInfo {
    typeName = OrganizationService.typeName;
    methods = OrganizationService.methods;
    options = OrganizationService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * List all organizations
     *
     * @generated from protobuf rpc: ListOrganizations
     */
    listOrganizations(input: ListOrganizationsRequest, options?: RpcOptions): UnaryCall<ListOrganizationsRequest, ListOrganizationsResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListOrganizationsRequest, ListOrganizationsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Get organization by ID
     *
     * @generated from protobuf rpc: GetOrganization
     */
    getOrganization(input: GetOrganizationRequest, options?: RpcOptions): UnaryCall<GetOrganizationRequest, OrganizationResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetOrganizationRequest, OrganizationResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Create organization
     *
     * @generated from protobuf rpc: CreateOrganization
     */
    createOrganization(input: CreateOrganizationRequest, options?: RpcOptions): UnaryCall<CreateOrganizationRequest, OrganizationResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreateOrganizationRequest, OrganizationResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Update organization
     *
     * @generated from protobuf rpc: UpdateOrganization
     */
    updateOrganization(input: UpdateOrganizationRequest, options?: RpcOptions): UnaryCall<UpdateOrganizationRequest, OrganizationResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateOrganizationRequest, OrganizationResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Delete organization
     *
     * @generated from protobuf rpc: DeleteOrganization
     */
    deleteOrganization(input: DeleteOrganizationRequest, options?: RpcOptions): UnaryCall<DeleteOrganizationRequest, Empty> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteOrganizationRequest, Empty>("unary", this._transport, method, opt, input);
    }
    /**
     * Invite user to organization
     *
     * @generated from protobuf rpc: InviteUser
     */
    inviteUser(input: InviteUserRequest, options?: RpcOptions): UnaryCall<InviteUserRequest, InviteUserResponse> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<InviteUserRequest, InviteUserResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Accept invitation
     *
     * @generated from protobuf rpc: AcceptInvitation
     */
    acceptInvitation(input: AcceptInvitationRequest, options?: RpcOptions): UnaryCall<AcceptInvitationRequest, Empty> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<AcceptInvitationRequest, Empty>("unary", this._transport, method, opt, input);
    }
    /**
     * List organization members
     *
     * @generated from protobuf rpc: ListMembers
     */
    listMembers(input: ListMembersRequest, options?: RpcOptions): UnaryCall<ListMembersRequest, ListMembersResponse> {
        const method = this.methods[7], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListMembersRequest, ListMembersResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Update member role
     *
     * @generated from protobuf rpc: UpdateMemberRole
     */
    updateMemberRole(input: UpdateMemberRoleRequest, options?: RpcOptions): UnaryCall<UpdateMemberRoleRequest, MemberResponse> {
        const method = this.methods[8], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateMemberRoleRequest, MemberResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Remove member from organization
     *
     * @generated from protobuf rpc: RemoveMember
     */
    removeMember(input: RemoveMemberRequest, options?: RpcOptions): UnaryCall<RemoveMemberRequest, Empty> {
        const method = this.methods[9], opt = this._transport.mergeOptions(options);
        return stackIntercept<RemoveMemberRequest, Empty>("unary", this._transport, method, opt, input);
    }
}
