// @generated by protobuf-ts 2.11.1 with parameter disable_ts_nocheck
// @generated from protobuf file "workspace/workspace.proto" (package "wws.workspace", syntax proto3)
// tslint:disable
import { Empty } from "../common/common";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { PaginationResponse } from "../common/common";
import { PaginationRequest } from "../common/common";
import { Timestamp } from "../common/common";
import { Status } from "../common/common";
/**
 * Workspace message
 *
 * @generated from protobuf message wws.workspace.Workspace
 */
export interface Workspace {
    /**
     * @generated from protobuf field: int32 id = 1
     */
    id: number;
    /**
     * @generated from protobuf field: string tag = 2
     */
    tag: string;
    /**
     * @generated from protobuf field: string name = 3
     */
    name: string;
    /**
     * @generated from protobuf field: int32 organization_id = 4
     */
    organizationId: number;
    /**
     * @generated from protobuf field: int32 owner_id = 5
     */
    ownerId: number;
    /**
     * @generated from protobuf field: string provider = 6
     */
    provider: string;
    /**
     * @generated from protobuf field: wws.common.Status status = 7
     */
    status: Status;
    /**
     * @generated from protobuf field: string endpoint = 8
     */
    endpoint: string;
    /**
     * @generated from protobuf field: string ssh_host = 9
     */
    sshHost: string;
    /**
     * @generated from protobuf field: int32 ssh_port = 10
     */
    sshPort: number;
    /**
     * @generated from protobuf field: string http_host = 11
     */
    httpHost: string;
    /**
     * @generated from protobuf field: int32 http_port = 12
     */
    httpPort: number;
    /**
     * @generated from protobuf field: string code_host = 13
     */
    codeHost: string;
    /**
     * @generated from protobuf field: int32 code_port = 14
     */
    codePort: number;
    /**
     * @generated from protobuf field: int32 cpu = 15
     */
    cpu: number;
    /**
     * @generated from protobuf field: int32 memory = 16
     */
    memory: number;
    /**
     * @generated from protobuf field: int32 storage = 17
     */
    storage: number;
    /**
     * @generated from protobuf field: string region = 18
     */
    region: string;
    /**
     * @generated from protobuf field: string config = 19
     */
    config: string;
    /**
     * @generated from protobuf field: wws.common.Timestamp created_at = 20
     */
    createdAt?: Timestamp;
    /**
     * @generated from protobuf field: wws.common.Timestamp updated_at = 21
     */
    updatedAt?: Timestamp;
}
/**
 * Language message
 *
 * @generated from protobuf message wws.workspace.Language
 */
export interface Language {
    /**
     * @generated from protobuf field: int32 id = 1
     */
    id: number;
    /**
     * @generated from protobuf field: int32 workspace_id = 2
     */
    workspaceId: number;
    /**
     * @generated from protobuf field: string name = 3
     */
    name: string;
    /**
     * @generated from protobuf field: string version = 4
     */
    version: string;
    /**
     * @generated from protobuf field: string install_script = 5
     */
    installScript: string;
    /**
     * @generated from protobuf field: wws.common.Timestamp installed_at = 6
     */
    installedAt?: Timestamp;
}
/**
 * ListWorkspacesRequest
 *
 * @generated from protobuf message wws.workspace.ListWorkspacesRequest
 */
export interface ListWorkspacesRequest {
    /**
     * @generated from protobuf field: int32 organization_id = 1
     */
    organizationId: number;
    /**
     * @generated from protobuf field: wws.common.PaginationRequest pagination = 2
     */
    pagination?: PaginationRequest;
}
/**
 * ListWorkspacesResponse
 *
 * @generated from protobuf message wws.workspace.ListWorkspacesResponse
 */
export interface ListWorkspacesResponse {
    /**
     * @generated from protobuf field: repeated wws.workspace.Workspace workspaces = 1
     */
    workspaces: Workspace[];
    /**
     * @generated from protobuf field: wws.common.PaginationResponse pagination = 2
     */
    pagination?: PaginationResponse;
}
/**
 * GetWorkspaceRequest
 *
 * @generated from protobuf message wws.workspace.GetWorkspaceRequest
 */
export interface GetWorkspaceRequest {
    /**
     * @generated from protobuf field: int32 id = 1
     */
    id: number;
}
/**
 * WorkspaceResponse
 *
 * @generated from protobuf message wws.workspace.WorkspaceResponse
 */
export interface WorkspaceResponse {
    /**
     * @generated from protobuf field: wws.workspace.Workspace workspace = 1
     */
    workspace?: Workspace;
}
/**
 * CreateWorkspaceRequest
 *
 * @generated from protobuf message wws.workspace.CreateWorkspaceRequest
 */
export interface CreateWorkspaceRequest {
    /**
     * @generated from protobuf field: string name = 1
     */
    name: string;
    /**
     * @generated from protobuf field: int32 organization_id = 2
     */
    organizationId: number;
    /**
     * @generated from protobuf field: int32 cpu = 3
     */
    cpu: number;
    /**
     * @generated from protobuf field: int32 memory = 4
     */
    memory: number;
    /**
     * @generated from protobuf field: int32 storage = 5
     */
    storage: number;
    /**
     * @generated from protobuf field: repeated string languages = 6
     */
    languages: string[];
    /**
     * @generated from protobuf field: string region = 7
     */
    region: string;
}
/**
 * UpdateWorkspaceRequest
 *
 * @generated from protobuf message wws.workspace.UpdateWorkspaceRequest
 */
export interface UpdateWorkspaceRequest {
    /**
     * @generated from protobuf field: int32 id = 1
     */
    id: number;
    /**
     * @generated from protobuf field: string name = 2
     */
    name: string;
    /**
     * @generated from protobuf field: int32 cpu = 3
     */
    cpu: number;
    /**
     * @generated from protobuf field: int32 memory = 4
     */
    memory: number;
    /**
     * @generated from protobuf field: int32 storage = 5
     */
    storage: number;
    /**
     * @generated from protobuf field: repeated string languages = 6
     */
    languages: string[];
    /**
     * @generated from protobuf field: string region = 7
     */
    region: string;
}
/**
 * DeleteWorkspaceRequest
 *
 * @generated from protobuf message wws.workspace.DeleteWorkspaceRequest
 */
export interface DeleteWorkspaceRequest {
    /**
     * @generated from protobuf field: int32 id = 1
     */
    id: number;
}
/**
 * StartWorkspaceRequest
 *
 * @generated from protobuf message wws.workspace.StartWorkspaceRequest
 */
export interface StartWorkspaceRequest {
    /**
     * @generated from protobuf field: int32 id = 1
     */
    id: number;
}
/**
 * StopWorkspaceRequest
 *
 * @generated from protobuf message wws.workspace.StopWorkspaceRequest
 */
export interface StopWorkspaceRequest {
    /**
     * @generated from protobuf field: int32 id = 1
     */
    id: number;
}
/**
 * RestartWorkspaceRequest
 *
 * @generated from protobuf message wws.workspace.RestartWorkspaceRequest
 */
export interface RestartWorkspaceRequest {
    /**
     * @generated from protobuf field: int32 id = 1
     */
    id: number;
}
/**
 * GetWorkspaceLogsRequest
 *
 * @generated from protobuf message wws.workspace.GetWorkspaceLogsRequest
 */
export interface GetWorkspaceLogsRequest {
    /**
     * @generated from protobuf field: int32 id = 1
     */
    id: number;
    /**
     * @generated from protobuf field: int32 tail_lines = 2
     */
    tailLines: number;
}
/**
 * WorkspaceLogsResponse
 *
 * @generated from protobuf message wws.workspace.WorkspaceLogsResponse
 */
export interface WorkspaceLogsResponse {
    /**
     * @generated from protobuf field: string logs = 1
     */
    logs: string;
}
/**
 * InstallLanguageRequest
 *
 * @generated from protobuf message wws.workspace.InstallLanguageRequest
 */
export interface InstallLanguageRequest {
    /**
     * @generated from protobuf field: int32 workspace_id = 1
     */
    workspaceId: number;
    /**
     * @generated from protobuf field: string language = 2
     */
    language: string;
    /**
     * @generated from protobuf field: string version = 3
     */
    version: string;
}
/**
 * InstallLanguageResponse
 *
 * @generated from protobuf message wws.workspace.InstallLanguageResponse
 */
export interface InstallLanguageResponse {
    /**
     * @generated from protobuf field: wws.workspace.Language language = 1
     */
    language?: Language;
}
/**
 * ListLanguagesRequest
 *
 * @generated from protobuf message wws.workspace.ListLanguagesRequest
 */
export interface ListLanguagesRequest {
    /**
     * @generated from protobuf field: int32 workspace_id = 1
     */
    workspaceId: number;
}
/**
 * ListLanguagesResponse
 *
 * @generated from protobuf message wws.workspace.ListLanguagesResponse
 */
export interface ListLanguagesResponse {
    /**
     * @generated from protobuf field: repeated wws.workspace.Language languages = 1
     */
    languages: Language[];
}
// @generated message type with reflection information, may provide speed optimized methods
class Workspace$Type extends MessageType<Workspace> {
    constructor() {
        super("wws.workspace.Workspace", [
            { no: 1, name: "id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "tag", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "organization_id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 5, name: "owner_id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 6, name: "provider", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "status", kind: "enum", T: () => ["wws.common.Status", Status, "STATUS_"] },
            { no: 8, name: "endpoint", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 9, name: "ssh_host", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 10, name: "ssh_port", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 11, name: "http_host", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 12, name: "http_port", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 13, name: "code_host", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 14, name: "code_port", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 15, name: "cpu", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 16, name: "memory", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 17, name: "storage", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 18, name: "region", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 19, name: "config", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 20, name: "created_at", kind: "message", T: () => Timestamp },
            { no: 21, name: "updated_at", kind: "message", T: () => Timestamp }
        ]);
    }
    create(value?: PartialMessage<Workspace>): Workspace {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = 0;
        message.tag = "";
        message.name = "";
        message.organizationId = 0;
        message.ownerId = 0;
        message.provider = "";
        message.status = 0;
        message.endpoint = "";
        message.sshHost = "";
        message.sshPort = 0;
        message.httpHost = "";
        message.httpPort = 0;
        message.codeHost = "";
        message.codePort = 0;
        message.cpu = 0;
        message.memory = 0;
        message.storage = 0;
        message.region = "";
        message.config = "";
        if (value !== undefined)
            reflectionMergePartial<Workspace>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Workspace): Workspace {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 id */ 1:
                    message.id = reader.int32();
                    break;
                case /* string tag */ 2:
                    message.tag = reader.string();
                    break;
                case /* string name */ 3:
                    message.name = reader.string();
                    break;
                case /* int32 organization_id */ 4:
                    message.organizationId = reader.int32();
                    break;
                case /* int32 owner_id */ 5:
                    message.ownerId = reader.int32();
                    break;
                case /* string provider */ 6:
                    message.provider = reader.string();
                    break;
                case /* wws.common.Status status */ 7:
                    message.status = reader.int32();
                    break;
                case /* string endpoint */ 8:
                    message.endpoint = reader.string();
                    break;
                case /* string ssh_host */ 9:
                    message.sshHost = reader.string();
                    break;
                case /* int32 ssh_port */ 10:
                    message.sshPort = reader.int32();
                    break;
                case /* string http_host */ 11:
                    message.httpHost = reader.string();
                    break;
                case /* int32 http_port */ 12:
                    message.httpPort = reader.int32();
                    break;
                case /* string code_host */ 13:
                    message.codeHost = reader.string();
                    break;
                case /* int32 code_port */ 14:
                    message.codePort = reader.int32();
                    break;
                case /* int32 cpu */ 15:
                    message.cpu = reader.int32();
                    break;
                case /* int32 memory */ 16:
                    message.memory = reader.int32();
                    break;
                case /* int32 storage */ 17:
                    message.storage = reader.int32();
                    break;
                case /* string region */ 18:
                    message.region = reader.string();
                    break;
                case /* string config */ 19:
                    message.config = reader.string();
                    break;
                case /* wws.common.Timestamp created_at */ 20:
                    message.createdAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.createdAt);
                    break;
                case /* wws.common.Timestamp updated_at */ 21:
                    message.updatedAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.updatedAt);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Workspace, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 id = 1; */
        if (message.id !== 0)
            writer.tag(1, WireType.Varint).int32(message.id);
        /* string tag = 2; */
        if (message.tag !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.tag);
        /* string name = 3; */
        if (message.name !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.name);
        /* int32 organization_id = 4; */
        if (message.organizationId !== 0)
            writer.tag(4, WireType.Varint).int32(message.organizationId);
        /* int32 owner_id = 5; */
        if (message.ownerId !== 0)
            writer.tag(5, WireType.Varint).int32(message.ownerId);
        /* string provider = 6; */
        if (message.provider !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.provider);
        /* wws.common.Status status = 7; */
        if (message.status !== 0)
            writer.tag(7, WireType.Varint).int32(message.status);
        /* string endpoint = 8; */
        if (message.endpoint !== "")
            writer.tag(8, WireType.LengthDelimited).string(message.endpoint);
        /* string ssh_host = 9; */
        if (message.sshHost !== "")
            writer.tag(9, WireType.LengthDelimited).string(message.sshHost);
        /* int32 ssh_port = 10; */
        if (message.sshPort !== 0)
            writer.tag(10, WireType.Varint).int32(message.sshPort);
        /* string http_host = 11; */
        if (message.httpHost !== "")
            writer.tag(11, WireType.LengthDelimited).string(message.httpHost);
        /* int32 http_port = 12; */
        if (message.httpPort !== 0)
            writer.tag(12, WireType.Varint).int32(message.httpPort);
        /* string code_host = 13; */
        if (message.codeHost !== "")
            writer.tag(13, WireType.LengthDelimited).string(message.codeHost);
        /* int32 code_port = 14; */
        if (message.codePort !== 0)
            writer.tag(14, WireType.Varint).int32(message.codePort);
        /* int32 cpu = 15; */
        if (message.cpu !== 0)
            writer.tag(15, WireType.Varint).int32(message.cpu);
        /* int32 memory = 16; */
        if (message.memory !== 0)
            writer.tag(16, WireType.Varint).int32(message.memory);
        /* int32 storage = 17; */
        if (message.storage !== 0)
            writer.tag(17, WireType.Varint).int32(message.storage);
        /* string region = 18; */
        if (message.region !== "")
            writer.tag(18, WireType.LengthDelimited).string(message.region);
        /* string config = 19; */
        if (message.config !== "")
            writer.tag(19, WireType.LengthDelimited).string(message.config);
        /* wws.common.Timestamp created_at = 20; */
        if (message.createdAt)
            Timestamp.internalBinaryWrite(message.createdAt, writer.tag(20, WireType.LengthDelimited).fork(), options).join();
        /* wws.common.Timestamp updated_at = 21; */
        if (message.updatedAt)
            Timestamp.internalBinaryWrite(message.updatedAt, writer.tag(21, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wws.workspace.Workspace
 */
export const Workspace = new Workspace$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Language$Type extends MessageType<Language> {
    constructor() {
        super("wws.workspace.Language", [
            { no: 1, name: "id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "workspace_id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "version", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "install_script", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "installed_at", kind: "message", T: () => Timestamp }
        ]);
    }
    create(value?: PartialMessage<Language>): Language {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = 0;
        message.workspaceId = 0;
        message.name = "";
        message.version = "";
        message.installScript = "";
        if (value !== undefined)
            reflectionMergePartial<Language>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Language): Language {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 id */ 1:
                    message.id = reader.int32();
                    break;
                case /* int32 workspace_id */ 2:
                    message.workspaceId = reader.int32();
                    break;
                case /* string name */ 3:
                    message.name = reader.string();
                    break;
                case /* string version */ 4:
                    message.version = reader.string();
                    break;
                case /* string install_script */ 5:
                    message.installScript = reader.string();
                    break;
                case /* wws.common.Timestamp installed_at */ 6:
                    message.installedAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.installedAt);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Language, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 id = 1; */
        if (message.id !== 0)
            writer.tag(1, WireType.Varint).int32(message.id);
        /* int32 workspace_id = 2; */
        if (message.workspaceId !== 0)
            writer.tag(2, WireType.Varint).int32(message.workspaceId);
        /* string name = 3; */
        if (message.name !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.name);
        /* string version = 4; */
        if (message.version !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.version);
        /* string install_script = 5; */
        if (message.installScript !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.installScript);
        /* wws.common.Timestamp installed_at = 6; */
        if (message.installedAt)
            Timestamp.internalBinaryWrite(message.installedAt, writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wws.workspace.Language
 */
export const Language = new Language$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListWorkspacesRequest$Type extends MessageType<ListWorkspacesRequest> {
    constructor() {
        super("wws.workspace.ListWorkspacesRequest", [
            { no: 1, name: "organization_id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "pagination", kind: "message", T: () => PaginationRequest }
        ]);
    }
    create(value?: PartialMessage<ListWorkspacesRequest>): ListWorkspacesRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.organizationId = 0;
        if (value !== undefined)
            reflectionMergePartial<ListWorkspacesRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListWorkspacesRequest): ListWorkspacesRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 organization_id */ 1:
                    message.organizationId = reader.int32();
                    break;
                case /* wws.common.PaginationRequest pagination */ 2:
                    message.pagination = PaginationRequest.internalBinaryRead(reader, reader.uint32(), options, message.pagination);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListWorkspacesRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 organization_id = 1; */
        if (message.organizationId !== 0)
            writer.tag(1, WireType.Varint).int32(message.organizationId);
        /* wws.common.PaginationRequest pagination = 2; */
        if (message.pagination)
            PaginationRequest.internalBinaryWrite(message.pagination, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wws.workspace.ListWorkspacesRequest
 */
export const ListWorkspacesRequest = new ListWorkspacesRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListWorkspacesResponse$Type extends MessageType<ListWorkspacesResponse> {
    constructor() {
        super("wws.workspace.ListWorkspacesResponse", [
            { no: 1, name: "workspaces", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Workspace },
            { no: 2, name: "pagination", kind: "message", T: () => PaginationResponse }
        ]);
    }
    create(value?: PartialMessage<ListWorkspacesResponse>): ListWorkspacesResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.workspaces = [];
        if (value !== undefined)
            reflectionMergePartial<ListWorkspacesResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListWorkspacesResponse): ListWorkspacesResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated wws.workspace.Workspace workspaces */ 1:
                    message.workspaces.push(Workspace.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* wws.common.PaginationResponse pagination */ 2:
                    message.pagination = PaginationResponse.internalBinaryRead(reader, reader.uint32(), options, message.pagination);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListWorkspacesResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated wws.workspace.Workspace workspaces = 1; */
        for (let i = 0; i < message.workspaces.length; i++)
            Workspace.internalBinaryWrite(message.workspaces[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* wws.common.PaginationResponse pagination = 2; */
        if (message.pagination)
            PaginationResponse.internalBinaryWrite(message.pagination, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wws.workspace.ListWorkspacesResponse
 */
export const ListWorkspacesResponse = new ListWorkspacesResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetWorkspaceRequest$Type extends MessageType<GetWorkspaceRequest> {
    constructor() {
        super("wws.workspace.GetWorkspaceRequest", [
            { no: 1, name: "id", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<GetWorkspaceRequest>): GetWorkspaceRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = 0;
        if (value !== undefined)
            reflectionMergePartial<GetWorkspaceRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetWorkspaceRequest): GetWorkspaceRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 id */ 1:
                    message.id = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetWorkspaceRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 id = 1; */
        if (message.id !== 0)
            writer.tag(1, WireType.Varint).int32(message.id);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wws.workspace.GetWorkspaceRequest
 */
export const GetWorkspaceRequest = new GetWorkspaceRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class WorkspaceResponse$Type extends MessageType<WorkspaceResponse> {
    constructor() {
        super("wws.workspace.WorkspaceResponse", [
            { no: 1, name: "workspace", kind: "message", T: () => Workspace }
        ]);
    }
    create(value?: PartialMessage<WorkspaceResponse>): WorkspaceResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<WorkspaceResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: WorkspaceResponse): WorkspaceResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* wws.workspace.Workspace workspace */ 1:
                    message.workspace = Workspace.internalBinaryRead(reader, reader.uint32(), options, message.workspace);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: WorkspaceResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* wws.workspace.Workspace workspace = 1; */
        if (message.workspace)
            Workspace.internalBinaryWrite(message.workspace, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wws.workspace.WorkspaceResponse
 */
export const WorkspaceResponse = new WorkspaceResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CreateWorkspaceRequest$Type extends MessageType<CreateWorkspaceRequest> {
    constructor() {
        super("wws.workspace.CreateWorkspaceRequest", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "organization_id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "cpu", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "memory", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 5, name: "storage", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 6, name: "languages", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "region", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<CreateWorkspaceRequest>): CreateWorkspaceRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.name = "";
        message.organizationId = 0;
        message.cpu = 0;
        message.memory = 0;
        message.storage = 0;
        message.languages = [];
        message.region = "";
        if (value !== undefined)
            reflectionMergePartial<CreateWorkspaceRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreateWorkspaceRequest): CreateWorkspaceRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string name */ 1:
                    message.name = reader.string();
                    break;
                case /* int32 organization_id */ 2:
                    message.organizationId = reader.int32();
                    break;
                case /* int32 cpu */ 3:
                    message.cpu = reader.int32();
                    break;
                case /* int32 memory */ 4:
                    message.memory = reader.int32();
                    break;
                case /* int32 storage */ 5:
                    message.storage = reader.int32();
                    break;
                case /* repeated string languages */ 6:
                    message.languages.push(reader.string());
                    break;
                case /* string region */ 7:
                    message.region = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CreateWorkspaceRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string name = 1; */
        if (message.name !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.name);
        /* int32 organization_id = 2; */
        if (message.organizationId !== 0)
            writer.tag(2, WireType.Varint).int32(message.organizationId);
        /* int32 cpu = 3; */
        if (message.cpu !== 0)
            writer.tag(3, WireType.Varint).int32(message.cpu);
        /* int32 memory = 4; */
        if (message.memory !== 0)
            writer.tag(4, WireType.Varint).int32(message.memory);
        /* int32 storage = 5; */
        if (message.storage !== 0)
            writer.tag(5, WireType.Varint).int32(message.storage);
        /* repeated string languages = 6; */
        for (let i = 0; i < message.languages.length; i++)
            writer.tag(6, WireType.LengthDelimited).string(message.languages[i]);
        /* string region = 7; */
        if (message.region !== "")
            writer.tag(7, WireType.LengthDelimited).string(message.region);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wws.workspace.CreateWorkspaceRequest
 */
export const CreateWorkspaceRequest = new CreateWorkspaceRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdateWorkspaceRequest$Type extends MessageType<UpdateWorkspaceRequest> {
    constructor() {
        super("wws.workspace.UpdateWorkspaceRequest", [
            { no: 1, name: "id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "cpu", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "memory", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 5, name: "storage", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 6, name: "languages", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "region", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<UpdateWorkspaceRequest>): UpdateWorkspaceRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = 0;
        message.name = "";
        message.cpu = 0;
        message.memory = 0;
        message.storage = 0;
        message.languages = [];
        message.region = "";
        if (value !== undefined)
            reflectionMergePartial<UpdateWorkspaceRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UpdateWorkspaceRequest): UpdateWorkspaceRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 id */ 1:
                    message.id = reader.int32();
                    break;
                case /* string name */ 2:
                    message.name = reader.string();
                    break;
                case /* int32 cpu */ 3:
                    message.cpu = reader.int32();
                    break;
                case /* int32 memory */ 4:
                    message.memory = reader.int32();
                    break;
                case /* int32 storage */ 5:
                    message.storage = reader.int32();
                    break;
                case /* repeated string languages */ 6:
                    message.languages.push(reader.string());
                    break;
                case /* string region */ 7:
                    message.region = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UpdateWorkspaceRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 id = 1; */
        if (message.id !== 0)
            writer.tag(1, WireType.Varint).int32(message.id);
        /* string name = 2; */
        if (message.name !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.name);
        /* int32 cpu = 3; */
        if (message.cpu !== 0)
            writer.tag(3, WireType.Varint).int32(message.cpu);
        /* int32 memory = 4; */
        if (message.memory !== 0)
            writer.tag(4, WireType.Varint).int32(message.memory);
        /* int32 storage = 5; */
        if (message.storage !== 0)
            writer.tag(5, WireType.Varint).int32(message.storage);
        /* repeated string languages = 6; */
        for (let i = 0; i < message.languages.length; i++)
            writer.tag(6, WireType.LengthDelimited).string(message.languages[i]);
        /* string region = 7; */
        if (message.region !== "")
            writer.tag(7, WireType.LengthDelimited).string(message.region);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wws.workspace.UpdateWorkspaceRequest
 */
export const UpdateWorkspaceRequest = new UpdateWorkspaceRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeleteWorkspaceRequest$Type extends MessageType<DeleteWorkspaceRequest> {
    constructor() {
        super("wws.workspace.DeleteWorkspaceRequest", [
            { no: 1, name: "id", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<DeleteWorkspaceRequest>): DeleteWorkspaceRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = 0;
        if (value !== undefined)
            reflectionMergePartial<DeleteWorkspaceRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DeleteWorkspaceRequest): DeleteWorkspaceRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 id */ 1:
                    message.id = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DeleteWorkspaceRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 id = 1; */
        if (message.id !== 0)
            writer.tag(1, WireType.Varint).int32(message.id);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wws.workspace.DeleteWorkspaceRequest
 */
export const DeleteWorkspaceRequest = new DeleteWorkspaceRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class StartWorkspaceRequest$Type extends MessageType<StartWorkspaceRequest> {
    constructor() {
        super("wws.workspace.StartWorkspaceRequest", [
            { no: 1, name: "id", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<StartWorkspaceRequest>): StartWorkspaceRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = 0;
        if (value !== undefined)
            reflectionMergePartial<StartWorkspaceRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: StartWorkspaceRequest): StartWorkspaceRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 id */ 1:
                    message.id = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: StartWorkspaceRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 id = 1; */
        if (message.id !== 0)
            writer.tag(1, WireType.Varint).int32(message.id);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wws.workspace.StartWorkspaceRequest
 */
export const StartWorkspaceRequest = new StartWorkspaceRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class StopWorkspaceRequest$Type extends MessageType<StopWorkspaceRequest> {
    constructor() {
        super("wws.workspace.StopWorkspaceRequest", [
            { no: 1, name: "id", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<StopWorkspaceRequest>): StopWorkspaceRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = 0;
        if (value !== undefined)
            reflectionMergePartial<StopWorkspaceRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: StopWorkspaceRequest): StopWorkspaceRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 id */ 1:
                    message.id = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: StopWorkspaceRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 id = 1; */
        if (message.id !== 0)
            writer.tag(1, WireType.Varint).int32(message.id);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wws.workspace.StopWorkspaceRequest
 */
export const StopWorkspaceRequest = new StopWorkspaceRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RestartWorkspaceRequest$Type extends MessageType<RestartWorkspaceRequest> {
    constructor() {
        super("wws.workspace.RestartWorkspaceRequest", [
            { no: 1, name: "id", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<RestartWorkspaceRequest>): RestartWorkspaceRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = 0;
        if (value !== undefined)
            reflectionMergePartial<RestartWorkspaceRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RestartWorkspaceRequest): RestartWorkspaceRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 id */ 1:
                    message.id = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RestartWorkspaceRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 id = 1; */
        if (message.id !== 0)
            writer.tag(1, WireType.Varint).int32(message.id);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wws.workspace.RestartWorkspaceRequest
 */
export const RestartWorkspaceRequest = new RestartWorkspaceRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetWorkspaceLogsRequest$Type extends MessageType<GetWorkspaceLogsRequest> {
    constructor() {
        super("wws.workspace.GetWorkspaceLogsRequest", [
            { no: 1, name: "id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "tail_lines", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<GetWorkspaceLogsRequest>): GetWorkspaceLogsRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = 0;
        message.tailLines = 0;
        if (value !== undefined)
            reflectionMergePartial<GetWorkspaceLogsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetWorkspaceLogsRequest): GetWorkspaceLogsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 id */ 1:
                    message.id = reader.int32();
                    break;
                case /* int32 tail_lines */ 2:
                    message.tailLines = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetWorkspaceLogsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 id = 1; */
        if (message.id !== 0)
            writer.tag(1, WireType.Varint).int32(message.id);
        /* int32 tail_lines = 2; */
        if (message.tailLines !== 0)
            writer.tag(2, WireType.Varint).int32(message.tailLines);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wws.workspace.GetWorkspaceLogsRequest
 */
export const GetWorkspaceLogsRequest = new GetWorkspaceLogsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class WorkspaceLogsResponse$Type extends MessageType<WorkspaceLogsResponse> {
    constructor() {
        super("wws.workspace.WorkspaceLogsResponse", [
            { no: 1, name: "logs", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<WorkspaceLogsResponse>): WorkspaceLogsResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.logs = "";
        if (value !== undefined)
            reflectionMergePartial<WorkspaceLogsResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: WorkspaceLogsResponse): WorkspaceLogsResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string logs */ 1:
                    message.logs = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: WorkspaceLogsResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string logs = 1; */
        if (message.logs !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.logs);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wws.workspace.WorkspaceLogsResponse
 */
export const WorkspaceLogsResponse = new WorkspaceLogsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class InstallLanguageRequest$Type extends MessageType<InstallLanguageRequest> {
    constructor() {
        super("wws.workspace.InstallLanguageRequest", [
            { no: 1, name: "workspace_id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "language", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "version", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<InstallLanguageRequest>): InstallLanguageRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.workspaceId = 0;
        message.language = "";
        message.version = "";
        if (value !== undefined)
            reflectionMergePartial<InstallLanguageRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: InstallLanguageRequest): InstallLanguageRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 workspace_id */ 1:
                    message.workspaceId = reader.int32();
                    break;
                case /* string language */ 2:
                    message.language = reader.string();
                    break;
                case /* string version */ 3:
                    message.version = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: InstallLanguageRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 workspace_id = 1; */
        if (message.workspaceId !== 0)
            writer.tag(1, WireType.Varint).int32(message.workspaceId);
        /* string language = 2; */
        if (message.language !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.language);
        /* string version = 3; */
        if (message.version !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.version);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wws.workspace.InstallLanguageRequest
 */
export const InstallLanguageRequest = new InstallLanguageRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class InstallLanguageResponse$Type extends MessageType<InstallLanguageResponse> {
    constructor() {
        super("wws.workspace.InstallLanguageResponse", [
            { no: 1, name: "language", kind: "message", T: () => Language }
        ]);
    }
    create(value?: PartialMessage<InstallLanguageResponse>): InstallLanguageResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<InstallLanguageResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: InstallLanguageResponse): InstallLanguageResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* wws.workspace.Language language */ 1:
                    message.language = Language.internalBinaryRead(reader, reader.uint32(), options, message.language);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: InstallLanguageResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* wws.workspace.Language language = 1; */
        if (message.language)
            Language.internalBinaryWrite(message.language, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wws.workspace.InstallLanguageResponse
 */
export const InstallLanguageResponse = new InstallLanguageResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListLanguagesRequest$Type extends MessageType<ListLanguagesRequest> {
    constructor() {
        super("wws.workspace.ListLanguagesRequest", [
            { no: 1, name: "workspace_id", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<ListLanguagesRequest>): ListLanguagesRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.workspaceId = 0;
        if (value !== undefined)
            reflectionMergePartial<ListLanguagesRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListLanguagesRequest): ListLanguagesRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 workspace_id */ 1:
                    message.workspaceId = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListLanguagesRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 workspace_id = 1; */
        if (message.workspaceId !== 0)
            writer.tag(1, WireType.Varint).int32(message.workspaceId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wws.workspace.ListLanguagesRequest
 */
export const ListLanguagesRequest = new ListLanguagesRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListLanguagesResponse$Type extends MessageType<ListLanguagesResponse> {
    constructor() {
        super("wws.workspace.ListLanguagesResponse", [
            { no: 1, name: "languages", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Language }
        ]);
    }
    create(value?: PartialMessage<ListLanguagesResponse>): ListLanguagesResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.languages = [];
        if (value !== undefined)
            reflectionMergePartial<ListLanguagesResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListLanguagesResponse): ListLanguagesResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated wws.workspace.Language languages */ 1:
                    message.languages.push(Language.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListLanguagesResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated wws.workspace.Language languages = 1; */
        for (let i = 0; i < message.languages.length; i++)
            Language.internalBinaryWrite(message.languages[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wws.workspace.ListLanguagesResponse
 */
export const ListLanguagesResponse = new ListLanguagesResponse$Type();
/**
 * @generated ServiceType for protobuf service wws.workspace.WorkspaceService
 */
export const WorkspaceService = new ServiceType("wws.workspace.WorkspaceService", [
    { name: "ListWorkspaces", options: {}, I: ListWorkspacesRequest, O: ListWorkspacesResponse },
    { name: "GetWorkspace", options: {}, I: GetWorkspaceRequest, O: WorkspaceResponse },
    { name: "CreateWorkspace", options: {}, I: CreateWorkspaceRequest, O: WorkspaceResponse },
    { name: "UpdateWorkspace", options: {}, I: UpdateWorkspaceRequest, O: WorkspaceResponse },
    { name: "DeleteWorkspace", options: {}, I: DeleteWorkspaceRequest, O: Empty },
    { name: "StartWorkspace", options: {}, I: StartWorkspaceRequest, O: WorkspaceResponse },
    { name: "StopWorkspace", options: {}, I: StopWorkspaceRequest, O: WorkspaceResponse },
    { name: "RestartWorkspace", options: {}, I: RestartWorkspaceRequest, O: WorkspaceResponse },
    { name: "GetWorkspaceLogs", options: {}, I: GetWorkspaceLogsRequest, O: WorkspaceLogsResponse },
    { name: "InstallLanguage", options: {}, I: InstallLanguageRequest, O: InstallLanguageResponse },
    { name: "ListLanguages", options: {}, I: ListLanguagesRequest, O: ListLanguagesResponse }
]);
