// @generated by protobuf-ts 2.11.1 with parameter disable_ts_nocheck
// @generated from protobuf file "workspace/workspace.proto" (package "wws.workspace", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { WorkspaceService } from "./workspace";
import type { ListLanguagesResponse } from "./workspace";
import type { ListLanguagesRequest } from "./workspace";
import type { InstallLanguageResponse } from "./workspace";
import type { InstallLanguageRequest } from "./workspace";
import type { WorkspaceLogsResponse } from "./workspace";
import type { GetWorkspaceLogsRequest } from "./workspace";
import type { RestartWorkspaceRequest } from "./workspace";
import type { StopWorkspaceRequest } from "./workspace";
import type { StartWorkspaceRequest } from "./workspace";
import type { Empty } from "../common/common";
import type { DeleteWorkspaceRequest } from "./workspace";
import type { UpdateWorkspaceRequest } from "./workspace";
import type { CreateWorkspaceRequest } from "./workspace";
import type { WorkspaceResponse } from "./workspace";
import type { GetWorkspaceRequest } from "./workspace";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { ListWorkspacesResponse } from "./workspace";
import type { ListWorkspacesRequest } from "./workspace";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * Workspace service definition
 *
 * @generated from protobuf service wws.workspace.WorkspaceService
 */
export interface IWorkspaceServiceClient {
    /**
     * List all workspaces for an organization
     *
     * @generated from protobuf rpc: ListWorkspaces
     */
    listWorkspaces(input: ListWorkspacesRequest, options?: RpcOptions): UnaryCall<ListWorkspacesRequest, ListWorkspacesResponse>;
    /**
     * Get workspace by ID
     *
     * @generated from protobuf rpc: GetWorkspace
     */
    getWorkspace(input: GetWorkspaceRequest, options?: RpcOptions): UnaryCall<GetWorkspaceRequest, WorkspaceResponse>;
    /**
     * Create workspace
     *
     * @generated from protobuf rpc: CreateWorkspace
     */
    createWorkspace(input: CreateWorkspaceRequest, options?: RpcOptions): UnaryCall<CreateWorkspaceRequest, WorkspaceResponse>;
    /**
     * Update workspace
     *
     * @generated from protobuf rpc: UpdateWorkspace
     */
    updateWorkspace(input: UpdateWorkspaceRequest, options?: RpcOptions): UnaryCall<UpdateWorkspaceRequest, WorkspaceResponse>;
    /**
     * Delete workspace
     *
     * @generated from protobuf rpc: DeleteWorkspace
     */
    deleteWorkspace(input: DeleteWorkspaceRequest, options?: RpcOptions): UnaryCall<DeleteWorkspaceRequest, Empty>;
    /**
     * Start workspace
     *
     * @generated from protobuf rpc: StartWorkspace
     */
    startWorkspace(input: StartWorkspaceRequest, options?: RpcOptions): UnaryCall<StartWorkspaceRequest, WorkspaceResponse>;
    /**
     * Stop workspace
     *
     * @generated from protobuf rpc: StopWorkspace
     */
    stopWorkspace(input: StopWorkspaceRequest, options?: RpcOptions): UnaryCall<StopWorkspaceRequest, WorkspaceResponse>;
    /**
     * Restart workspace
     *
     * @generated from protobuf rpc: RestartWorkspace
     */
    restartWorkspace(input: RestartWorkspaceRequest, options?: RpcOptions): UnaryCall<RestartWorkspaceRequest, WorkspaceResponse>;
    /**
     * Get workspace logs
     *
     * @generated from protobuf rpc: GetWorkspaceLogs
     */
    getWorkspaceLogs(input: GetWorkspaceLogsRequest, options?: RpcOptions): UnaryCall<GetWorkspaceLogsRequest, WorkspaceLogsResponse>;
    /**
     * Install language in workspace
     *
     * @generated from protobuf rpc: InstallLanguage
     */
    installLanguage(input: InstallLanguageRequest, options?: RpcOptions): UnaryCall<InstallLanguageRequest, InstallLanguageResponse>;
    /**
     * List installed languages
     *
     * @generated from protobuf rpc: ListLanguages
     */
    listLanguages(input: ListLanguagesRequest, options?: RpcOptions): UnaryCall<ListLanguagesRequest, ListLanguagesResponse>;
}
/**
 * Workspace service definition
 *
 * @generated from protobuf service wws.workspace.WorkspaceService
 */
export class WorkspaceServiceClient implements IWorkspaceServiceClient, ServiceInfo {
    typeName = WorkspaceService.typeName;
    methods = WorkspaceService.methods;
    options = WorkspaceService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * List all workspaces for an organization
     *
     * @generated from protobuf rpc: ListWorkspaces
     */
    listWorkspaces(input: ListWorkspacesRequest, options?: RpcOptions): UnaryCall<ListWorkspacesRequest, ListWorkspacesResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListWorkspacesRequest, ListWorkspacesResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Get workspace by ID
     *
     * @generated from protobuf rpc: GetWorkspace
     */
    getWorkspace(input: GetWorkspaceRequest, options?: RpcOptions): UnaryCall<GetWorkspaceRequest, WorkspaceResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetWorkspaceRequest, WorkspaceResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Create workspace
     *
     * @generated from protobuf rpc: CreateWorkspace
     */
    createWorkspace(input: CreateWorkspaceRequest, options?: RpcOptions): UnaryCall<CreateWorkspaceRequest, WorkspaceResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreateWorkspaceRequest, WorkspaceResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Update workspace
     *
     * @generated from protobuf rpc: UpdateWorkspace
     */
    updateWorkspace(input: UpdateWorkspaceRequest, options?: RpcOptions): UnaryCall<UpdateWorkspaceRequest, WorkspaceResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateWorkspaceRequest, WorkspaceResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Delete workspace
     *
     * @generated from protobuf rpc: DeleteWorkspace
     */
    deleteWorkspace(input: DeleteWorkspaceRequest, options?: RpcOptions): UnaryCall<DeleteWorkspaceRequest, Empty> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteWorkspaceRequest, Empty>("unary", this._transport, method, opt, input);
    }
    /**
     * Start workspace
     *
     * @generated from protobuf rpc: StartWorkspace
     */
    startWorkspace(input: StartWorkspaceRequest, options?: RpcOptions): UnaryCall<StartWorkspaceRequest, WorkspaceResponse> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<StartWorkspaceRequest, WorkspaceResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Stop workspace
     *
     * @generated from protobuf rpc: StopWorkspace
     */
    stopWorkspace(input: StopWorkspaceRequest, options?: RpcOptions): UnaryCall<StopWorkspaceRequest, WorkspaceResponse> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<StopWorkspaceRequest, WorkspaceResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Restart workspace
     *
     * @generated from protobuf rpc: RestartWorkspace
     */
    restartWorkspace(input: RestartWorkspaceRequest, options?: RpcOptions): UnaryCall<RestartWorkspaceRequest, WorkspaceResponse> {
        const method = this.methods[7], opt = this._transport.mergeOptions(options);
        return stackIntercept<RestartWorkspaceRequest, WorkspaceResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Get workspace logs
     *
     * @generated from protobuf rpc: GetWorkspaceLogs
     */
    getWorkspaceLogs(input: GetWorkspaceLogsRequest, options?: RpcOptions): UnaryCall<GetWorkspaceLogsRequest, WorkspaceLogsResponse> {
        const method = this.methods[8], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetWorkspaceLogsRequest, WorkspaceLogsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Install language in workspace
     *
     * @generated from protobuf rpc: InstallLanguage
     */
    installLanguage(input: InstallLanguageRequest, options?: RpcOptions): UnaryCall<InstallLanguageRequest, InstallLanguageResponse> {
        const method = this.methods[9], opt = this._transport.mergeOptions(options);
        return stackIntercept<InstallLanguageRequest, InstallLanguageResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * List installed languages
     *
     * @generated from protobuf rpc: ListLanguages
     */
    listLanguages(input: ListLanguagesRequest, options?: RpcOptions): UnaryCall<ListLanguagesRequest, ListLanguagesResponse> {
        const method = this.methods[10], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListLanguagesRequest, ListLanguagesResponse>("unary", this._transport, method, opt, input);
    }
}
