// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: organization/organization.proto

package organization

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
	common "wws/api/proto/common"
	user "wws/api/proto/user"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Organization message
type Organization struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	OwnerId       int32                  `protobuf:"varint,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,5,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	CreatedAt     *common.Timestamp      `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *common.Timestamp      `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Organization) Reset() {
	*x = Organization{}
	mi := &file_organization_organization_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Organization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Organization) ProtoMessage() {}

func (x *Organization) ProtoReflect() protoreflect.Message {
	mi := &file_organization_organization_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Organization.ProtoReflect.Descriptor instead.
func (*Organization) Descriptor() ([]byte, []int) {
	return file_organization_organization_proto_rawDescGZIP(), []int{0}
}

func (x *Organization) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Organization) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Organization) GetOwnerId() int32 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *Organization) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Organization) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *Organization) GetCreatedAt() *common.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Organization) GetUpdatedAt() *common.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Member message
type Member struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	User          *user.User             `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"` // admin, member, viewer
	Accepted      bool                   `protobuf:"varint,4,opt,name=accepted,proto3" json:"accepted,omitempty"`
	InvitedAt     *common.Timestamp      `protobuf:"bytes,5,opt,name=invited_at,json=invitedAt,proto3" json:"invited_at,omitempty"`
	JoinedAt      *common.Timestamp      `protobuf:"bytes,6,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Member) Reset() {
	*x = Member{}
	mi := &file_organization_organization_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Member) ProtoMessage() {}

func (x *Member) ProtoReflect() protoreflect.Message {
	mi := &file_organization_organization_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Member.ProtoReflect.Descriptor instead.
func (*Member) Descriptor() ([]byte, []int) {
	return file_organization_organization_proto_rawDescGZIP(), []int{1}
}

func (x *Member) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Member) GetUser() *user.User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *Member) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Member) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *Member) GetInvitedAt() *common.Timestamp {
	if x != nil {
		return x.InvitedAt
	}
	return nil
}

func (x *Member) GetJoinedAt() *common.Timestamp {
	if x != nil {
		return x.JoinedAt
	}
	return nil
}

// Invitation message
type Invitation struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrganizationId int32                  `protobuf:"varint,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Email          string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Role           string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	InvitedBy      int32                  `protobuf:"varint,5,opt,name=invited_by,json=invitedBy,proto3" json:"invited_by,omitempty"`
	Accepted       bool                   `protobuf:"varint,6,opt,name=accepted,proto3" json:"accepted,omitempty"`
	ExpiresAt      *common.Timestamp      `protobuf:"bytes,7,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	CreatedAt      *common.Timestamp      `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Invitation) Reset() {
	*x = Invitation{}
	mi := &file_organization_organization_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Invitation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Invitation) ProtoMessage() {}

func (x *Invitation) ProtoReflect() protoreflect.Message {
	mi := &file_organization_organization_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Invitation.ProtoReflect.Descriptor instead.
func (*Invitation) Descriptor() ([]byte, []int) {
	return file_organization_organization_proto_rawDescGZIP(), []int{2}
}

func (x *Invitation) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Invitation) GetOrganizationId() int32 {
	if x != nil {
		return x.OrganizationId
	}
	return 0
}

func (x *Invitation) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Invitation) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Invitation) GetInvitedBy() int32 {
	if x != nil {
		return x.InvitedBy
	}
	return 0
}

func (x *Invitation) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *Invitation) GetExpiresAt() *common.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *Invitation) GetCreatedAt() *common.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// ListOrganizationsRequest
type ListOrganizationsRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Pagination    *common.PaginationRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrganizationsRequest) Reset() {
	*x = ListOrganizationsRequest{}
	mi := &file_organization_organization_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrganizationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrganizationsRequest) ProtoMessage() {}

func (x *ListOrganizationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_organization_organization_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrganizationsRequest.ProtoReflect.Descriptor instead.
func (*ListOrganizationsRequest) Descriptor() ([]byte, []int) {
	return file_organization_organization_proto_rawDescGZIP(), []int{3}
}

func (x *ListOrganizationsRequest) GetPagination() *common.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// ListOrganizationsResponse
type ListOrganizationsResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Organizations []*Organization            `protobuf:"bytes,1,rep,name=organizations,proto3" json:"organizations,omitempty"`
	Pagination    *common.PaginationResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrganizationsResponse) Reset() {
	*x = ListOrganizationsResponse{}
	mi := &file_organization_organization_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrganizationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrganizationsResponse) ProtoMessage() {}

func (x *ListOrganizationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_organization_organization_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrganizationsResponse.ProtoReflect.Descriptor instead.
func (*ListOrganizationsResponse) Descriptor() ([]byte, []int) {
	return file_organization_organization_proto_rawDescGZIP(), []int{4}
}

func (x *ListOrganizationsResponse) GetOrganizations() []*Organization {
	if x != nil {
		return x.Organizations
	}
	return nil
}

func (x *ListOrganizationsResponse) GetPagination() *common.PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// GetOrganizationRequest
type GetOrganizationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrganizationRequest) Reset() {
	*x = GetOrganizationRequest{}
	mi := &file_organization_organization_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrganizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrganizationRequest) ProtoMessage() {}

func (x *GetOrganizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_organization_organization_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrganizationRequest.ProtoReflect.Descriptor instead.
func (*GetOrganizationRequest) Descriptor() ([]byte, []int) {
	return file_organization_organization_proto_rawDescGZIP(), []int{5}
}

func (x *GetOrganizationRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// OrganizationResponse
type OrganizationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Organization  *Organization          `protobuf:"bytes,1,opt,name=organization,proto3" json:"organization,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrganizationResponse) Reset() {
	*x = OrganizationResponse{}
	mi := &file_organization_organization_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrganizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrganizationResponse) ProtoMessage() {}

func (x *OrganizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_organization_organization_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrganizationResponse.ProtoReflect.Descriptor instead.
func (*OrganizationResponse) Descriptor() ([]byte, []int) {
	return file_organization_organization_proto_rawDescGZIP(), []int{6}
}

func (x *OrganizationResponse) GetOrganization() *Organization {
	if x != nil {
		return x.Organization
	}
	return nil
}

// CreateOrganizationRequest
type CreateOrganizationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrganizationRequest) Reset() {
	*x = CreateOrganizationRequest{}
	mi := &file_organization_organization_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrganizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrganizationRequest) ProtoMessage() {}

func (x *CreateOrganizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_organization_organization_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrganizationRequest.ProtoReflect.Descriptor instead.
func (*CreateOrganizationRequest) Descriptor() ([]byte, []int) {
	return file_organization_organization_proto_rawDescGZIP(), []int{7}
}

func (x *CreateOrganizationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateOrganizationRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// UpdateOrganizationRequest
type UpdateOrganizationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrganizationRequest) Reset() {
	*x = UpdateOrganizationRequest{}
	mi := &file_organization_organization_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrganizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrganizationRequest) ProtoMessage() {}

func (x *UpdateOrganizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_organization_organization_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrganizationRequest.ProtoReflect.Descriptor instead.
func (*UpdateOrganizationRequest) Descriptor() ([]byte, []int) {
	return file_organization_organization_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateOrganizationRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateOrganizationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateOrganizationRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// DeleteOrganizationRequest
type DeleteOrganizationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOrganizationRequest) Reset() {
	*x = DeleteOrganizationRequest{}
	mi := &file_organization_organization_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOrganizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOrganizationRequest) ProtoMessage() {}

func (x *DeleteOrganizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_organization_organization_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOrganizationRequest.ProtoReflect.Descriptor instead.
func (*DeleteOrganizationRequest) Descriptor() ([]byte, []int) {
	return file_organization_organization_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteOrganizationRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// InviteUserRequest
type InviteUserRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId int32                  `protobuf:"varint,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Email          string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Role           string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InviteUserRequest) Reset() {
	*x = InviteUserRequest{}
	mi := &file_organization_organization_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteUserRequest) ProtoMessage() {}

func (x *InviteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_organization_organization_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteUserRequest.ProtoReflect.Descriptor instead.
func (*InviteUserRequest) Descriptor() ([]byte, []int) {
	return file_organization_organization_proto_rawDescGZIP(), []int{10}
}

func (x *InviteUserRequest) GetOrganizationId() int32 {
	if x != nil {
		return x.OrganizationId
	}
	return 0
}

func (x *InviteUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *InviteUserRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

// InviteUserResponse
type InviteUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Invitation    *Invitation            `protobuf:"bytes,1,opt,name=invitation,proto3" json:"invitation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteUserResponse) Reset() {
	*x = InviteUserResponse{}
	mi := &file_organization_organization_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteUserResponse) ProtoMessage() {}

func (x *InviteUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_organization_organization_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteUserResponse.ProtoReflect.Descriptor instead.
func (*InviteUserResponse) Descriptor() ([]byte, []int) {
	return file_organization_organization_proto_rawDescGZIP(), []int{11}
}

func (x *InviteUserResponse) GetInvitation() *Invitation {
	if x != nil {
		return x.Invitation
	}
	return nil
}

// AcceptInvitationRequest
type AcceptInvitationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InvitationId  int32                  `protobuf:"varint,1,opt,name=invitation_id,json=invitationId,proto3" json:"invitation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptInvitationRequest) Reset() {
	*x = AcceptInvitationRequest{}
	mi := &file_organization_organization_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptInvitationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptInvitationRequest) ProtoMessage() {}

func (x *AcceptInvitationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_organization_organization_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptInvitationRequest.ProtoReflect.Descriptor instead.
func (*AcceptInvitationRequest) Descriptor() ([]byte, []int) {
	return file_organization_organization_proto_rawDescGZIP(), []int{12}
}

func (x *AcceptInvitationRequest) GetInvitationId() int32 {
	if x != nil {
		return x.InvitationId
	}
	return 0
}

// ListMembersRequest
type ListMembersRequest struct {
	state          protoimpl.MessageState    `protogen:"open.v1"`
	OrganizationId int32                     `protobuf:"varint,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Pagination     *common.PaginationRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListMembersRequest) Reset() {
	*x = ListMembersRequest{}
	mi := &file_organization_organization_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersRequest) ProtoMessage() {}

func (x *ListMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_organization_organization_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersRequest.ProtoReflect.Descriptor instead.
func (*ListMembersRequest) Descriptor() ([]byte, []int) {
	return file_organization_organization_proto_rawDescGZIP(), []int{13}
}

func (x *ListMembersRequest) GetOrganizationId() int32 {
	if x != nil {
		return x.OrganizationId
	}
	return 0
}

func (x *ListMembersRequest) GetPagination() *common.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// ListMembersResponse
type ListMembersResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Members       []*Member                  `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	Pagination    *common.PaginationResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembersResponse) Reset() {
	*x = ListMembersResponse{}
	mi := &file_organization_organization_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersResponse) ProtoMessage() {}

func (x *ListMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_organization_organization_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersResponse.ProtoReflect.Descriptor instead.
func (*ListMembersResponse) Descriptor() ([]byte, []int) {
	return file_organization_organization_proto_rawDescGZIP(), []int{14}
}

func (x *ListMembersResponse) GetMembers() []*Member {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *ListMembersResponse) GetPagination() *common.PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// MemberResponse
type MemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Member        *Member                `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberResponse) Reset() {
	*x = MemberResponse{}
	mi := &file_organization_organization_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberResponse) ProtoMessage() {}

func (x *MemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_organization_organization_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberResponse.ProtoReflect.Descriptor instead.
func (*MemberResponse) Descriptor() ([]byte, []int) {
	return file_organization_organization_proto_rawDescGZIP(), []int{15}
}

func (x *MemberResponse) GetMember() *Member {
	if x != nil {
		return x.Member
	}
	return nil
}

// UpdateMemberRoleRequest
type UpdateMemberRoleRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId int32                  `protobuf:"varint,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	UserId         int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role           string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateMemberRoleRequest) Reset() {
	*x = UpdateMemberRoleRequest{}
	mi := &file_organization_organization_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMemberRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMemberRoleRequest) ProtoMessage() {}

func (x *UpdateMemberRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_organization_organization_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMemberRoleRequest.ProtoReflect.Descriptor instead.
func (*UpdateMemberRoleRequest) Descriptor() ([]byte, []int) {
	return file_organization_organization_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateMemberRoleRequest) GetOrganizationId() int32 {
	if x != nil {
		return x.OrganizationId
	}
	return 0
}

func (x *UpdateMemberRoleRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateMemberRoleRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

// RemoveMemberRequest
type RemoveMemberRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId int32                  `protobuf:"varint,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	UserId         int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RemoveMemberRequest) Reset() {
	*x = RemoveMemberRequest{}
	mi := &file_organization_organization_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMemberRequest) ProtoMessage() {}

func (x *RemoveMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_organization_organization_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMemberRequest.ProtoReflect.Descriptor instead.
func (*RemoveMemberRequest) Descriptor() ([]byte, []int) {
	return file_organization_organization_proto_rawDescGZIP(), []int{17}
}

func (x *RemoveMemberRequest) GetOrganizationId() int32 {
	if x != nil {
		return x.OrganizationId
	}
	return 0
}

func (x *RemoveMemberRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

var File_organization_organization_proto protoreflect.FileDescriptor

const file_organization_organization_proto_rawDesc = "" +
	"\n" +
	"\x1forganization/organization.proto\x12\x10wws.organization\x1a\x13common/common.proto\x1a\x0fuser/user.proto\"\xfa\x01\n" +
	"\fOrganization\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\bowner_id\x18\x03 \x01(\x05R\aownerId\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x05 \x01(\tR\tavatarUrl\x124\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x15.wws.common.TimestampR\tcreatedAt\x124\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x15.wws.common.TimestampR\tupdatedAt\"\xd6\x01\n" +
	"\x06Member\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\"\n" +
	"\x04user\x18\x02 \x01(\v2\x0e.wws.user.UserR\x04user\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x1a\n" +
	"\baccepted\x18\x04 \x01(\bR\baccepted\x124\n" +
	"\n" +
	"invited_at\x18\x05 \x01(\v2\x15.wws.common.TimestampR\tinvitedAt\x122\n" +
	"\tjoined_at\x18\x06 \x01(\v2\x15.wws.common.TimestampR\bjoinedAt\"\x96\x02\n" +
	"\n" +
	"Invitation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\x05R\x0eorganizationId\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12\x1d\n" +
	"\n" +
	"invited_by\x18\x05 \x01(\x05R\tinvitedBy\x12\x1a\n" +
	"\baccepted\x18\x06 \x01(\bR\baccepted\x124\n" +
	"\n" +
	"expires_at\x18\a \x01(\v2\x15.wws.common.TimestampR\texpiresAt\x124\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x15.wws.common.TimestampR\tcreatedAt\"Y\n" +
	"\x18ListOrganizationsRequest\x12=\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x1d.wws.common.PaginationRequestR\n" +
	"pagination\"\xa1\x01\n" +
	"\x19ListOrganizationsResponse\x12D\n" +
	"\rorganizations\x18\x01 \x03(\v2\x1e.wws.organization.OrganizationR\rorganizations\x12>\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1e.wws.common.PaginationResponseR\n" +
	"pagination\"(\n" +
	"\x16GetOrganizationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"Z\n" +
	"\x14OrganizationResponse\x12B\n" +
	"\forganization\x18\x01 \x01(\v2\x1e.wws.organization.OrganizationR\forganization\"Q\n" +
	"\x19CreateOrganizationRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"a\n" +
	"\x19UpdateOrganizationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"+\n" +
	"\x19DeleteOrganizationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"f\n" +
	"\x11InviteUserRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\x05R\x0eorganizationId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\"R\n" +
	"\x12InviteUserResponse\x12<\n" +
	"\n" +
	"invitation\x18\x01 \x01(\v2\x1c.wws.organization.InvitationR\n" +
	"invitation\">\n" +
	"\x17AcceptInvitationRequest\x12#\n" +
	"\rinvitation_id\x18\x01 \x01(\x05R\finvitationId\"|\n" +
	"\x12ListMembersRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\x05R\x0eorganizationId\x12=\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1d.wws.common.PaginationRequestR\n" +
	"pagination\"\x89\x01\n" +
	"\x13ListMembersResponse\x122\n" +
	"\amembers\x18\x01 \x03(\v2\x18.wws.organization.MemberR\amembers\x12>\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1e.wws.common.PaginationResponseR\n" +
	"pagination\"B\n" +
	"\x0eMemberResponse\x120\n" +
	"\x06member\x18\x01 \x01(\v2\x18.wws.organization.MemberR\x06member\"o\n" +
	"\x17UpdateMemberRoleRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\x05R\x0eorganizationId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\"W\n" +
	"\x13RemoveMemberRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\x05R\x0eorganizationId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId2\xc6\a\n" +
	"\x13OrganizationService\x12l\n" +
	"\x11ListOrganizations\x12*.wws.organization.ListOrganizationsRequest\x1a+.wws.organization.ListOrganizationsResponse\x12c\n" +
	"\x0fGetOrganization\x12(.wws.organization.GetOrganizationRequest\x1a&.wws.organization.OrganizationResponse\x12i\n" +
	"\x12CreateOrganization\x12+.wws.organization.CreateOrganizationRequest\x1a&.wws.organization.OrganizationResponse\x12i\n" +
	"\x12UpdateOrganization\x12+.wws.organization.UpdateOrganizationRequest\x1a&.wws.organization.OrganizationResponse\x12T\n" +
	"\x12DeleteOrganization\x12+.wws.organization.DeleteOrganizationRequest\x1a\x11.wws.common.Empty\x12W\n" +
	"\n" +
	"InviteUser\x12#.wws.organization.InviteUserRequest\x1a$.wws.organization.InviteUserResponse\x12P\n" +
	"\x10AcceptInvitation\x12).wws.organization.AcceptInvitationRequest\x1a\x11.wws.common.Empty\x12Z\n" +
	"\vListMembers\x12$.wws.organization.ListMembersRequest\x1a%.wws.organization.ListMembersResponse\x12_\n" +
	"\x10UpdateMemberRole\x12).wws.organization.UpdateMemberRoleRequest\x1a .wws.organization.MemberResponse\x12H\n" +
	"\fRemoveMember\x12%.wws.organization.RemoveMemberRequest\x1a\x11.wws.common.EmptyB\x1cZ\x1awws/api/proto/organizationb\x06proto3"

var (
	file_organization_organization_proto_rawDescOnce sync.Once
	file_organization_organization_proto_rawDescData []byte
)

func file_organization_organization_proto_rawDescGZIP() []byte {
	file_organization_organization_proto_rawDescOnce.Do(func() {
		file_organization_organization_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_organization_organization_proto_rawDesc), len(file_organization_organization_proto_rawDesc)))
	})
	return file_organization_organization_proto_rawDescData
}

var file_organization_organization_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_organization_organization_proto_goTypes = []any{
	(*Organization)(nil),              // 0: wws.organization.Organization
	(*Member)(nil),                    // 1: wws.organization.Member
	(*Invitation)(nil),                // 2: wws.organization.Invitation
	(*ListOrganizationsRequest)(nil),  // 3: wws.organization.ListOrganizationsRequest
	(*ListOrganizationsResponse)(nil), // 4: wws.organization.ListOrganizationsResponse
	(*GetOrganizationRequest)(nil),    // 5: wws.organization.GetOrganizationRequest
	(*OrganizationResponse)(nil),      // 6: wws.organization.OrganizationResponse
	(*CreateOrganizationRequest)(nil), // 7: wws.organization.CreateOrganizationRequest
	(*UpdateOrganizationRequest)(nil), // 8: wws.organization.UpdateOrganizationRequest
	(*DeleteOrganizationRequest)(nil), // 9: wws.organization.DeleteOrganizationRequest
	(*InviteUserRequest)(nil),         // 10: wws.organization.InviteUserRequest
	(*InviteUserResponse)(nil),        // 11: wws.organization.InviteUserResponse
	(*AcceptInvitationRequest)(nil),   // 12: wws.organization.AcceptInvitationRequest
	(*ListMembersRequest)(nil),        // 13: wws.organization.ListMembersRequest
	(*ListMembersResponse)(nil),       // 14: wws.organization.ListMembersResponse
	(*MemberResponse)(nil),            // 15: wws.organization.MemberResponse
	(*UpdateMemberRoleRequest)(nil),   // 16: wws.organization.UpdateMemberRoleRequest
	(*RemoveMemberRequest)(nil),       // 17: wws.organization.RemoveMemberRequest
	(*common.Timestamp)(nil),          // 18: wws.common.Timestamp
	(*user.User)(nil),                 // 19: wws.user.User
	(*common.PaginationRequest)(nil),  // 20: wws.common.PaginationRequest
	(*common.PaginationResponse)(nil), // 21: wws.common.PaginationResponse
	(*common.Empty)(nil),              // 22: wws.common.Empty
}
var file_organization_organization_proto_depIdxs = []int32{
	18, // 0: wws.organization.Organization.created_at:type_name -> wws.common.Timestamp
	18, // 1: wws.organization.Organization.updated_at:type_name -> wws.common.Timestamp
	19, // 2: wws.organization.Member.user:type_name -> wws.user.User
	18, // 3: wws.organization.Member.invited_at:type_name -> wws.common.Timestamp
	18, // 4: wws.organization.Member.joined_at:type_name -> wws.common.Timestamp
	18, // 5: wws.organization.Invitation.expires_at:type_name -> wws.common.Timestamp
	18, // 6: wws.organization.Invitation.created_at:type_name -> wws.common.Timestamp
	20, // 7: wws.organization.ListOrganizationsRequest.pagination:type_name -> wws.common.PaginationRequest
	0,  // 8: wws.organization.ListOrganizationsResponse.organizations:type_name -> wws.organization.Organization
	21, // 9: wws.organization.ListOrganizationsResponse.pagination:type_name -> wws.common.PaginationResponse
	0,  // 10: wws.organization.OrganizationResponse.organization:type_name -> wws.organization.Organization
	2,  // 11: wws.organization.InviteUserResponse.invitation:type_name -> wws.organization.Invitation
	20, // 12: wws.organization.ListMembersRequest.pagination:type_name -> wws.common.PaginationRequest
	1,  // 13: wws.organization.ListMembersResponse.members:type_name -> wws.organization.Member
	21, // 14: wws.organization.ListMembersResponse.pagination:type_name -> wws.common.PaginationResponse
	1,  // 15: wws.organization.MemberResponse.member:type_name -> wws.organization.Member
	3,  // 16: wws.organization.OrganizationService.ListOrganizations:input_type -> wws.organization.ListOrganizationsRequest
	5,  // 17: wws.organization.OrganizationService.GetOrganization:input_type -> wws.organization.GetOrganizationRequest
	7,  // 18: wws.organization.OrganizationService.CreateOrganization:input_type -> wws.organization.CreateOrganizationRequest
	8,  // 19: wws.organization.OrganizationService.UpdateOrganization:input_type -> wws.organization.UpdateOrganizationRequest
	9,  // 20: wws.organization.OrganizationService.DeleteOrganization:input_type -> wws.organization.DeleteOrganizationRequest
	10, // 21: wws.organization.OrganizationService.InviteUser:input_type -> wws.organization.InviteUserRequest
	12, // 22: wws.organization.OrganizationService.AcceptInvitation:input_type -> wws.organization.AcceptInvitationRequest
	13, // 23: wws.organization.OrganizationService.ListMembers:input_type -> wws.organization.ListMembersRequest
	16, // 24: wws.organization.OrganizationService.UpdateMemberRole:input_type -> wws.organization.UpdateMemberRoleRequest
	17, // 25: wws.organization.OrganizationService.RemoveMember:input_type -> wws.organization.RemoveMemberRequest
	4,  // 26: wws.organization.OrganizationService.ListOrganizations:output_type -> wws.organization.ListOrganizationsResponse
	6,  // 27: wws.organization.OrganizationService.GetOrganization:output_type -> wws.organization.OrganizationResponse
	6,  // 28: wws.organization.OrganizationService.CreateOrganization:output_type -> wws.organization.OrganizationResponse
	6,  // 29: wws.organization.OrganizationService.UpdateOrganization:output_type -> wws.organization.OrganizationResponse
	22, // 30: wws.organization.OrganizationService.DeleteOrganization:output_type -> wws.common.Empty
	11, // 31: wws.organization.OrganizationService.InviteUser:output_type -> wws.organization.InviteUserResponse
	22, // 32: wws.organization.OrganizationService.AcceptInvitation:output_type -> wws.common.Empty
	14, // 33: wws.organization.OrganizationService.ListMembers:output_type -> wws.organization.ListMembersResponse
	15, // 34: wws.organization.OrganizationService.UpdateMemberRole:output_type -> wws.organization.MemberResponse
	22, // 35: wws.organization.OrganizationService.RemoveMember:output_type -> wws.common.Empty
	26, // [26:36] is the sub-list for method output_type
	16, // [16:26] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_organization_organization_proto_init() }
func file_organization_organization_proto_init() {
	if File_organization_organization_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_organization_organization_proto_rawDesc), len(file_organization_organization_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_organization_organization_proto_goTypes,
		DependencyIndexes: file_organization_organization_proto_depIdxs,
		MessageInfos:      file_organization_organization_proto_msgTypes,
	}.Build()
	File_organization_organization_proto = out.File
	file_organization_organization_proto_goTypes = nil
	file_organization_organization_proto_depIdxs = nil
}
