// @generated by protobuf-ts 2.11.1 with parameter disable_ts_nocheck
// @generated from protobuf file "auth/auth.proto" (package "wws.auth", syntax proto3)
// tslint:disable
import { Empty } from "../common/common";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { Timestamp } from "../common/common";
import { User } from "../user/user";
/**
 * GitHubAuthRequest
 *
 * @generated from protobuf message wws.auth.GitHubAuthRequest
 */
export interface GitHubAuthRequest {
}
/**
 * GitHubAuthResponse
 *
 * @generated from protobuf message wws.auth.GitHubAuthResponse
 */
export interface GitHubAuthResponse {
    /**
     * @generated from protobuf field: string auth_url = 1
     */
    authUrl: string;
    /**
     * @generated from protobuf field: string state = 2
     */
    state: string;
}
/**
 * GitHubCallbackRequest
 *
 * @generated from protobuf message wws.auth.GitHubCallbackRequest
 */
export interface GitHubCallbackRequest {
    /**
     * @generated from protobuf field: string code = 1
     */
    code: string;
    /**
     * @generated from protobuf field: string state = 2
     */
    state: string;
}
/**
 * GitHubCallbackResponse
 *
 * @generated from protobuf message wws.auth.GitHubCallbackResponse
 */
export interface GitHubCallbackResponse {
    /**
     * @generated from protobuf field: wws.user.User user = 1
     */
    user?: User;
    /**
     * @generated from protobuf field: string access_token = 2
     */
    accessToken: string;
    /**
     * @generated from protobuf field: bool new_user = 3
     */
    newUser: boolean;
}
/**
 * GetSessionRequest
 *
 * @generated from protobuf message wws.auth.GetSessionRequest
 */
export interface GetSessionRequest {
}
/**
 * SessionResponse
 *
 * @generated from protobuf message wws.auth.SessionResponse
 */
export interface SessionResponse {
    /**
     * @generated from protobuf field: bool authenticated = 1
     */
    authenticated: boolean;
    /**
     * @generated from protobuf field: wws.user.User user = 2
     */
    user?: User;
    /**
     * @generated from protobuf field: wws.common.Timestamp expires_at = 3
     */
    expiresAt?: Timestamp;
}
/**
 * LogoutRequest
 *
 * @generated from protobuf message wws.auth.LogoutRequest
 */
export interface LogoutRequest {
}
// @generated message type with reflection information, may provide speed optimized methods
class GitHubAuthRequest$Type extends MessageType<GitHubAuthRequest> {
    constructor() {
        super("wws.auth.GitHubAuthRequest", []);
    }
    create(value?: PartialMessage<GitHubAuthRequest>): GitHubAuthRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<GitHubAuthRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GitHubAuthRequest): GitHubAuthRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GitHubAuthRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wws.auth.GitHubAuthRequest
 */
export const GitHubAuthRequest = new GitHubAuthRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GitHubAuthResponse$Type extends MessageType<GitHubAuthResponse> {
    constructor() {
        super("wws.auth.GitHubAuthResponse", [
            { no: 1, name: "auth_url", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "state", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GitHubAuthResponse>): GitHubAuthResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.authUrl = "";
        message.state = "";
        if (value !== undefined)
            reflectionMergePartial<GitHubAuthResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GitHubAuthResponse): GitHubAuthResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string auth_url */ 1:
                    message.authUrl = reader.string();
                    break;
                case /* string state */ 2:
                    message.state = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GitHubAuthResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string auth_url = 1; */
        if (message.authUrl !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.authUrl);
        /* string state = 2; */
        if (message.state !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.state);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wws.auth.GitHubAuthResponse
 */
export const GitHubAuthResponse = new GitHubAuthResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GitHubCallbackRequest$Type extends MessageType<GitHubCallbackRequest> {
    constructor() {
        super("wws.auth.GitHubCallbackRequest", [
            { no: 1, name: "code", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "state", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GitHubCallbackRequest>): GitHubCallbackRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.code = "";
        message.state = "";
        if (value !== undefined)
            reflectionMergePartial<GitHubCallbackRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GitHubCallbackRequest): GitHubCallbackRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string code */ 1:
                    message.code = reader.string();
                    break;
                case /* string state */ 2:
                    message.state = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GitHubCallbackRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string code = 1; */
        if (message.code !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.code);
        /* string state = 2; */
        if (message.state !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.state);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wws.auth.GitHubCallbackRequest
 */
export const GitHubCallbackRequest = new GitHubCallbackRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GitHubCallbackResponse$Type extends MessageType<GitHubCallbackResponse> {
    constructor() {
        super("wws.auth.GitHubCallbackResponse", [
            { no: 1, name: "user", kind: "message", T: () => User },
            { no: 2, name: "access_token", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "new_user", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<GitHubCallbackResponse>): GitHubCallbackResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.accessToken = "";
        message.newUser = false;
        if (value !== undefined)
            reflectionMergePartial<GitHubCallbackResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GitHubCallbackResponse): GitHubCallbackResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* wws.user.User user */ 1:
                    message.user = User.internalBinaryRead(reader, reader.uint32(), options, message.user);
                    break;
                case /* string access_token */ 2:
                    message.accessToken = reader.string();
                    break;
                case /* bool new_user */ 3:
                    message.newUser = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GitHubCallbackResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* wws.user.User user = 1; */
        if (message.user)
            User.internalBinaryWrite(message.user, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* string access_token = 2; */
        if (message.accessToken !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.accessToken);
        /* bool new_user = 3; */
        if (message.newUser !== false)
            writer.tag(3, WireType.Varint).bool(message.newUser);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wws.auth.GitHubCallbackResponse
 */
export const GitHubCallbackResponse = new GitHubCallbackResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetSessionRequest$Type extends MessageType<GetSessionRequest> {
    constructor() {
        super("wws.auth.GetSessionRequest", []);
    }
    create(value?: PartialMessage<GetSessionRequest>): GetSessionRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<GetSessionRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetSessionRequest): GetSessionRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetSessionRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wws.auth.GetSessionRequest
 */
export const GetSessionRequest = new GetSessionRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SessionResponse$Type extends MessageType<SessionResponse> {
    constructor() {
        super("wws.auth.SessionResponse", [
            { no: 1, name: "authenticated", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "user", kind: "message", T: () => User },
            { no: 3, name: "expires_at", kind: "message", T: () => Timestamp }
        ]);
    }
    create(value?: PartialMessage<SessionResponse>): SessionResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.authenticated = false;
        if (value !== undefined)
            reflectionMergePartial<SessionResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SessionResponse): SessionResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool authenticated */ 1:
                    message.authenticated = reader.bool();
                    break;
                case /* wws.user.User user */ 2:
                    message.user = User.internalBinaryRead(reader, reader.uint32(), options, message.user);
                    break;
                case /* wws.common.Timestamp expires_at */ 3:
                    message.expiresAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.expiresAt);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SessionResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool authenticated = 1; */
        if (message.authenticated !== false)
            writer.tag(1, WireType.Varint).bool(message.authenticated);
        /* wws.user.User user = 2; */
        if (message.user)
            User.internalBinaryWrite(message.user, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* wws.common.Timestamp expires_at = 3; */
        if (message.expiresAt)
            Timestamp.internalBinaryWrite(message.expiresAt, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wws.auth.SessionResponse
 */
export const SessionResponse = new SessionResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class LogoutRequest$Type extends MessageType<LogoutRequest> {
    constructor() {
        super("wws.auth.LogoutRequest", []);
    }
    create(value?: PartialMessage<LogoutRequest>): LogoutRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<LogoutRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: LogoutRequest): LogoutRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: LogoutRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message wws.auth.LogoutRequest
 */
export const LogoutRequest = new LogoutRequest$Type();
/**
 * @generated ServiceType for protobuf service wws.auth.AuthService
 */
export const AuthService = new ServiceType("wws.auth.AuthService", [
    { name: "GitHubAuth", options: {}, I: GitHubAuthRequest, O: GitHubAuthResponse },
    { name: "GitHubCallback", options: {}, I: GitHubCallbackRequest, O: GitHubCallbackResponse },
    { name: "GetSession", options: {}, I: GetSessionRequest, O: SessionResponse },
    { name: "Logout", options: {}, I: LogoutRequest, O: Empty }
]);
