// @generated by protobuf-ts 2.11.1 with parameter disable_ts_nocheck
// @generated from protobuf file "auth/auth.proto" (package "wws.auth", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { AuthService } from "./auth";
import type { Empty } from "../common/common";
import type { LogoutRequest } from "./auth";
import type { SessionResponse } from "./auth";
import type { GetSessionRequest } from "./auth";
import type { GitHubCallbackResponse } from "./auth";
import type { GitHubCallbackRequest } from "./auth";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { GitHubAuthResponse } from "./auth";
import type { GitHubAuthRequest } from "./auth";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * AuthService definition
 *
 * @generated from protobuf service wws.auth.AuthService
 */
export interface IAuthServiceClient {
    /**
     * Initiate GitHub OAuth flow
     *
     * @generated from protobuf rpc: GitHubAuth
     */
    gitHubAuth(input: GitHubAuthRequest, options?: RpcOptions): UnaryCall<GitHubAuthRequest, GitHubAuthResponse>;
    /**
     * Handle GitHub OAuth callback
     *
     * @generated from protobuf rpc: GitHubCallback
     */
    gitHubCallback(input: GitHubCallbackRequest, options?: RpcOptions): UnaryCall<GitHubCallbackRequest, GitHubCallbackResponse>;
    /**
     * Get current session
     *
     * @generated from protobuf rpc: GetSession
     */
    getSession(input: GetSessionRequest, options?: RpcOptions): UnaryCall<GetSessionRequest, SessionResponse>;
    /**
     * Logout
     *
     * @generated from protobuf rpc: Logout
     */
    logout(input: LogoutRequest, options?: RpcOptions): UnaryCall<LogoutRequest, Empty>;
}
/**
 * AuthService definition
 *
 * @generated from protobuf service wws.auth.AuthService
 */
export class AuthServiceClient implements IAuthServiceClient, ServiceInfo {
    typeName = AuthService.typeName;
    methods = AuthService.methods;
    options = AuthService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * Initiate GitHub OAuth flow
     *
     * @generated from protobuf rpc: GitHubAuth
     */
    gitHubAuth(input: GitHubAuthRequest, options?: RpcOptions): UnaryCall<GitHubAuthRequest, GitHubAuthResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<GitHubAuthRequest, GitHubAuthResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Handle GitHub OAuth callback
     *
     * @generated from protobuf rpc: GitHubCallback
     */
    gitHubCallback(input: GitHubCallbackRequest, options?: RpcOptions): UnaryCall<GitHubCallbackRequest, GitHubCallbackResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<GitHubCallbackRequest, GitHubCallbackResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Get current session
     *
     * @generated from protobuf rpc: GetSession
     */
    getSession(input: GetSessionRequest, options?: RpcOptions): UnaryCall<GetSessionRequest, SessionResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetSessionRequest, SessionResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Logout
     *
     * @generated from protobuf rpc: Logout
     */
    logout(input: LogoutRequest, options?: RpcOptions): UnaryCall<LogoutRequest, Empty> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<LogoutRequest, Empty>("unary", this._transport, method, opt, input);
    }
}
