// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: auth/auth.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
	common "wws/api/proto/common"
	user "wws/api/proto/user"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GitHubAuthRequest
type GitHubAuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GitHubAuthRequest) Reset() {
	*x = GitHubAuthRequest{}
	mi := &file_auth_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitHubAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitHubAuthRequest) ProtoMessage() {}

func (x *GitHubAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitHubAuthRequest.ProtoReflect.Descriptor instead.
func (*GitHubAuthRequest) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{0}
}

// GitHubAuthResponse
type GitHubAuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthUrl       string                 `protobuf:"bytes,1,opt,name=auth_url,json=authUrl,proto3" json:"auth_url,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GitHubAuthResponse) Reset() {
	*x = GitHubAuthResponse{}
	mi := &file_auth_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitHubAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitHubAuthResponse) ProtoMessage() {}

func (x *GitHubAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitHubAuthResponse.ProtoReflect.Descriptor instead.
func (*GitHubAuthResponse) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{1}
}

func (x *GitHubAuthResponse) GetAuthUrl() string {
	if x != nil {
		return x.AuthUrl
	}
	return ""
}

func (x *GitHubAuthResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

// GitHubCallbackRequest
type GitHubCallbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GitHubCallbackRequest) Reset() {
	*x = GitHubCallbackRequest{}
	mi := &file_auth_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitHubCallbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitHubCallbackRequest) ProtoMessage() {}

func (x *GitHubCallbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitHubCallbackRequest.ProtoReflect.Descriptor instead.
func (*GitHubCallbackRequest) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{2}
}

func (x *GitHubCallbackRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GitHubCallbackRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

// GitHubCallbackResponse
type GitHubCallbackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *user.User             `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	NewUser       bool                   `protobuf:"varint,3,opt,name=new_user,json=newUser,proto3" json:"new_user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GitHubCallbackResponse) Reset() {
	*x = GitHubCallbackResponse{}
	mi := &file_auth_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitHubCallbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitHubCallbackResponse) ProtoMessage() {}

func (x *GitHubCallbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitHubCallbackResponse.ProtoReflect.Descriptor instead.
func (*GitHubCallbackResponse) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{3}
}

func (x *GitHubCallbackResponse) GetUser() *user.User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *GitHubCallbackResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *GitHubCallbackResponse) GetNewUser() bool {
	if x != nil {
		return x.NewUser
	}
	return false
}

// GetSessionRequest
type GetSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionRequest) Reset() {
	*x = GetSessionRequest{}
	mi := &file_auth_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionRequest) ProtoMessage() {}

func (x *GetSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionRequest.ProtoReflect.Descriptor instead.
func (*GetSessionRequest) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{4}
}

// SessionResponse
type SessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authenticated bool                   `protobuf:"varint,1,opt,name=authenticated,proto3" json:"authenticated,omitempty"`
	User          *user.User             `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	ExpiresAt     *common.Timestamp      `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionResponse) Reset() {
	*x = SessionResponse{}
	mi := &file_auth_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionResponse) ProtoMessage() {}

func (x *SessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionResponse.ProtoReflect.Descriptor instead.
func (*SessionResponse) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{5}
}

func (x *SessionResponse) GetAuthenticated() bool {
	if x != nil {
		return x.Authenticated
	}
	return false
}

func (x *SessionResponse) GetUser() *user.User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *SessionResponse) GetExpiresAt() *common.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

// LogoutRequest
type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_auth_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{6}
}

var File_auth_auth_proto protoreflect.FileDescriptor

const file_auth_auth_proto_rawDesc = "" +
	"\n" +
	"\x0fauth/auth.proto\x12\bwws.auth\x1a\x13common/common.proto\x1a\x0fuser/user.proto\"\x13\n" +
	"\x11GitHubAuthRequest\"E\n" +
	"\x12GitHubAuthResponse\x12\x19\n" +
	"\bauth_url\x18\x01 \x01(\tR\aauthUrl\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\"A\n" +
	"\x15GitHubCallbackRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\"z\n" +
	"\x16GitHubCallbackResponse\x12\"\n" +
	"\x04user\x18\x01 \x01(\v2\x0e.wws.user.UserR\x04user\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\x12\x19\n" +
	"\bnew_user\x18\x03 \x01(\bR\anewUser\"\x13\n" +
	"\x11GetSessionRequest\"\x91\x01\n" +
	"\x0fSessionResponse\x12$\n" +
	"\rauthenticated\x18\x01 \x01(\bR\rauthenticated\x12\"\n" +
	"\x04user\x18\x02 \x01(\v2\x0e.wws.user.UserR\x04user\x124\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x15.wws.common.TimestampR\texpiresAt\"\x0f\n" +
	"\rLogoutRequest2\xa7\x02\n" +
	"\vAuthService\x12G\n" +
	"\n" +
	"GitHubAuth\x12\x1b.wws.auth.GitHubAuthRequest\x1a\x1c.wws.auth.GitHubAuthResponse\x12S\n" +
	"\x0eGitHubCallback\x12\x1f.wws.auth.GitHubCallbackRequest\x1a .wws.auth.GitHubCallbackResponse\x12D\n" +
	"\n" +
	"GetSession\x12\x1b.wws.auth.GetSessionRequest\x1a\x19.wws.auth.SessionResponse\x124\n" +
	"\x06Logout\x12\x17.wws.auth.LogoutRequest\x1a\x11.wws.common.EmptyB\x14Z\x12wws/api/proto/authb\x06proto3"

var (
	file_auth_auth_proto_rawDescOnce sync.Once
	file_auth_auth_proto_rawDescData []byte
)

func file_auth_auth_proto_rawDescGZIP() []byte {
	file_auth_auth_proto_rawDescOnce.Do(func() {
		file_auth_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_auth_proto_rawDesc), len(file_auth_auth_proto_rawDesc)))
	})
	return file_auth_auth_proto_rawDescData
}

var file_auth_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_auth_auth_proto_goTypes = []any{
	(*GitHubAuthRequest)(nil),      // 0: wws.auth.GitHubAuthRequest
	(*GitHubAuthResponse)(nil),     // 1: wws.auth.GitHubAuthResponse
	(*GitHubCallbackRequest)(nil),  // 2: wws.auth.GitHubCallbackRequest
	(*GitHubCallbackResponse)(nil), // 3: wws.auth.GitHubCallbackResponse
	(*GetSessionRequest)(nil),      // 4: wws.auth.GetSessionRequest
	(*SessionResponse)(nil),        // 5: wws.auth.SessionResponse
	(*LogoutRequest)(nil),          // 6: wws.auth.LogoutRequest
	(*user.User)(nil),              // 7: wws.user.User
	(*common.Timestamp)(nil),       // 8: wws.common.Timestamp
	(*common.Empty)(nil),           // 9: wws.common.Empty
}
var file_auth_auth_proto_depIdxs = []int32{
	7, // 0: wws.auth.GitHubCallbackResponse.user:type_name -> wws.user.User
	7, // 1: wws.auth.SessionResponse.user:type_name -> wws.user.User
	8, // 2: wws.auth.SessionResponse.expires_at:type_name -> wws.common.Timestamp
	0, // 3: wws.auth.AuthService.GitHubAuth:input_type -> wws.auth.GitHubAuthRequest
	2, // 4: wws.auth.AuthService.GitHubCallback:input_type -> wws.auth.GitHubCallbackRequest
	4, // 5: wws.auth.AuthService.GetSession:input_type -> wws.auth.GetSessionRequest
	6, // 6: wws.auth.AuthService.Logout:input_type -> wws.auth.LogoutRequest
	1, // 7: wws.auth.AuthService.GitHubAuth:output_type -> wws.auth.GitHubAuthResponse
	3, // 8: wws.auth.AuthService.GitHubCallback:output_type -> wws.auth.GitHubCallbackResponse
	5, // 9: wws.auth.AuthService.GetSession:output_type -> wws.auth.SessionResponse
	9, // 10: wws.auth.AuthService.Logout:output_type -> wws.common.Empty
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_auth_auth_proto_init() }
func file_auth_auth_proto_init() {
	if File_auth_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_auth_proto_rawDesc), len(file_auth_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_auth_proto_goTypes,
		DependencyIndexes: file_auth_auth_proto_depIdxs,
		MessageInfos:      file_auth_auth_proto_msgTypes,
	}.Build()
	File_auth_auth_proto = out.File
	file_auth_auth_proto_goTypes = nil
	file_auth_auth_proto_depIdxs = nil
}
