// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: workspace/workspace.proto

package workspace

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
	common "wws/api/proto/common"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Workspace message
type Workspace struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Tag            string                 `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	OrganizationId int32                  `protobuf:"varint,4,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	OwnerId        int32                  `protobuf:"varint,5,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Provider       string                 `protobuf:"bytes,6,opt,name=provider,proto3" json:"provider,omitempty"`
	Status         common.Status          `protobuf:"varint,7,opt,name=status,proto3,enum=wws.common.Status" json:"status,omitempty"`
	Endpoint       string                 `protobuf:"bytes,8,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	SshHost        string                 `protobuf:"bytes,9,opt,name=ssh_host,json=sshHost,proto3" json:"ssh_host,omitempty"`
	SshPort        int32                  `protobuf:"varint,10,opt,name=ssh_port,json=sshPort,proto3" json:"ssh_port,omitempty"`
	HttpHost       string                 `protobuf:"bytes,11,opt,name=http_host,json=httpHost,proto3" json:"http_host,omitempty"`
	HttpPort       int32                  `protobuf:"varint,12,opt,name=http_port,json=httpPort,proto3" json:"http_port,omitempty"`
	CodeHost       string                 `protobuf:"bytes,13,opt,name=code_host,json=codeHost,proto3" json:"code_host,omitempty"`
	CodePort       int32                  `protobuf:"varint,14,opt,name=code_port,json=codePort,proto3" json:"code_port,omitempty"`
	Cpu            int32                  `protobuf:"varint,15,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory         int32                  `protobuf:"varint,16,opt,name=memory,proto3" json:"memory,omitempty"`
	Storage        int32                  `protobuf:"varint,17,opt,name=storage,proto3" json:"storage,omitempty"`
	Region         string                 `protobuf:"bytes,18,opt,name=region,proto3" json:"region,omitempty"`
	Config         string                 `protobuf:"bytes,19,opt,name=config,proto3" json:"config,omitempty"`
	CreatedAt      *common.Timestamp      `protobuf:"bytes,20,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *common.Timestamp      `protobuf:"bytes,21,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Workspace) Reset() {
	*x = Workspace{}
	mi := &file_workspace_workspace_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workspace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workspace) ProtoMessage() {}

func (x *Workspace) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_workspace_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workspace.ProtoReflect.Descriptor instead.
func (*Workspace) Descriptor() ([]byte, []int) {
	return file_workspace_workspace_proto_rawDescGZIP(), []int{0}
}

func (x *Workspace) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Workspace) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *Workspace) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Workspace) GetOrganizationId() int32 {
	if x != nil {
		return x.OrganizationId
	}
	return 0
}

func (x *Workspace) GetOwnerId() int32 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *Workspace) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *Workspace) GetStatus() common.Status {
	if x != nil {
		return x.Status
	}
	return common.Status(0)
}

func (x *Workspace) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *Workspace) GetSshHost() string {
	if x != nil {
		return x.SshHost
	}
	return ""
}

func (x *Workspace) GetSshPort() int32 {
	if x != nil {
		return x.SshPort
	}
	return 0
}

func (x *Workspace) GetHttpHost() string {
	if x != nil {
		return x.HttpHost
	}
	return ""
}

func (x *Workspace) GetHttpPort() int32 {
	if x != nil {
		return x.HttpPort
	}
	return 0
}

func (x *Workspace) GetCodeHost() string {
	if x != nil {
		return x.CodeHost
	}
	return ""
}

func (x *Workspace) GetCodePort() int32 {
	if x != nil {
		return x.CodePort
	}
	return 0
}

func (x *Workspace) GetCpu() int32 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

func (x *Workspace) GetMemory() int32 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *Workspace) GetStorage() int32 {
	if x != nil {
		return x.Storage
	}
	return 0
}

func (x *Workspace) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Workspace) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

func (x *Workspace) GetCreatedAt() *common.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Workspace) GetUpdatedAt() *common.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Language message
type Language struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	WorkspaceId   int32                  `protobuf:"varint,2,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	InstallScript string                 `protobuf:"bytes,5,opt,name=install_script,json=installScript,proto3" json:"install_script,omitempty"`
	InstalledAt   *common.Timestamp      `protobuf:"bytes,6,opt,name=installed_at,json=installedAt,proto3" json:"installed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Language) Reset() {
	*x = Language{}
	mi := &file_workspace_workspace_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Language) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Language) ProtoMessage() {}

func (x *Language) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_workspace_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Language.ProtoReflect.Descriptor instead.
func (*Language) Descriptor() ([]byte, []int) {
	return file_workspace_workspace_proto_rawDescGZIP(), []int{1}
}

func (x *Language) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Language) GetWorkspaceId() int32 {
	if x != nil {
		return x.WorkspaceId
	}
	return 0
}

func (x *Language) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Language) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Language) GetInstallScript() string {
	if x != nil {
		return x.InstallScript
	}
	return ""
}

func (x *Language) GetInstalledAt() *common.Timestamp {
	if x != nil {
		return x.InstalledAt
	}
	return nil
}

// ListWorkspacesRequest
type ListWorkspacesRequest struct {
	state          protoimpl.MessageState    `protogen:"open.v1"`
	OrganizationId int32                     `protobuf:"varint,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Pagination     *common.PaginationRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListWorkspacesRequest) Reset() {
	*x = ListWorkspacesRequest{}
	mi := &file_workspace_workspace_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkspacesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkspacesRequest) ProtoMessage() {}

func (x *ListWorkspacesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_workspace_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkspacesRequest.ProtoReflect.Descriptor instead.
func (*ListWorkspacesRequest) Descriptor() ([]byte, []int) {
	return file_workspace_workspace_proto_rawDescGZIP(), []int{2}
}

func (x *ListWorkspacesRequest) GetOrganizationId() int32 {
	if x != nil {
		return x.OrganizationId
	}
	return 0
}

func (x *ListWorkspacesRequest) GetPagination() *common.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// ListWorkspacesResponse
type ListWorkspacesResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Workspaces    []*Workspace               `protobuf:"bytes,1,rep,name=workspaces,proto3" json:"workspaces,omitempty"`
	Pagination    *common.PaginationResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkspacesResponse) Reset() {
	*x = ListWorkspacesResponse{}
	mi := &file_workspace_workspace_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkspacesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkspacesResponse) ProtoMessage() {}

func (x *ListWorkspacesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_workspace_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkspacesResponse.ProtoReflect.Descriptor instead.
func (*ListWorkspacesResponse) Descriptor() ([]byte, []int) {
	return file_workspace_workspace_proto_rawDescGZIP(), []int{3}
}

func (x *ListWorkspacesResponse) GetWorkspaces() []*Workspace {
	if x != nil {
		return x.Workspaces
	}
	return nil
}

func (x *ListWorkspacesResponse) GetPagination() *common.PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// GetWorkspaceRequest
type GetWorkspaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkspaceRequest) Reset() {
	*x = GetWorkspaceRequest{}
	mi := &file_workspace_workspace_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkspaceRequest) ProtoMessage() {}

func (x *GetWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_workspace_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*GetWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_workspace_workspace_proto_rawDescGZIP(), []int{4}
}

func (x *GetWorkspaceRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// WorkspaceResponse
type WorkspaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workspace     *Workspace             `protobuf:"bytes,1,opt,name=workspace,proto3" json:"workspace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkspaceResponse) Reset() {
	*x = WorkspaceResponse{}
	mi := &file_workspace_workspace_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceResponse) ProtoMessage() {}

func (x *WorkspaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_workspace_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceResponse.ProtoReflect.Descriptor instead.
func (*WorkspaceResponse) Descriptor() ([]byte, []int) {
	return file_workspace_workspace_proto_rawDescGZIP(), []int{5}
}

func (x *WorkspaceResponse) GetWorkspace() *Workspace {
	if x != nil {
		return x.Workspace
	}
	return nil
}

// CreateWorkspaceRequest
type CreateWorkspaceRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	OrganizationId int32                  `protobuf:"varint,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Cpu            int32                  `protobuf:"varint,3,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory         int32                  `protobuf:"varint,4,opt,name=memory,proto3" json:"memory,omitempty"`
	Storage        int32                  `protobuf:"varint,5,opt,name=storage,proto3" json:"storage,omitempty"`
	Languages      []string               `protobuf:"bytes,6,rep,name=languages,proto3" json:"languages,omitempty"`
	Region         string                 `protobuf:"bytes,7,opt,name=region,proto3" json:"region,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateWorkspaceRequest) Reset() {
	*x = CreateWorkspaceRequest{}
	mi := &file_workspace_workspace_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkspaceRequest) ProtoMessage() {}

func (x *CreateWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_workspace_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*CreateWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_workspace_workspace_proto_rawDescGZIP(), []int{6}
}

func (x *CreateWorkspaceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateWorkspaceRequest) GetOrganizationId() int32 {
	if x != nil {
		return x.OrganizationId
	}
	return 0
}

func (x *CreateWorkspaceRequest) GetCpu() int32 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

func (x *CreateWorkspaceRequest) GetMemory() int32 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *CreateWorkspaceRequest) GetStorage() int32 {
	if x != nil {
		return x.Storage
	}
	return 0
}

func (x *CreateWorkspaceRequest) GetLanguages() []string {
	if x != nil {
		return x.Languages
	}
	return nil
}

func (x *CreateWorkspaceRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

// UpdateWorkspaceRequest
type UpdateWorkspaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Cpu           int32                  `protobuf:"varint,3,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory        int32                  `protobuf:"varint,4,opt,name=memory,proto3" json:"memory,omitempty"`
	Storage       int32                  `protobuf:"varint,5,opt,name=storage,proto3" json:"storage,omitempty"`
	Languages     []string               `protobuf:"bytes,6,rep,name=languages,proto3" json:"languages,omitempty"`
	Region        string                 `protobuf:"bytes,7,opt,name=region,proto3" json:"region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWorkspaceRequest) Reset() {
	*x = UpdateWorkspaceRequest{}
	mi := &file_workspace_workspace_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWorkspaceRequest) ProtoMessage() {}

func (x *UpdateWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_workspace_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*UpdateWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_workspace_workspace_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateWorkspaceRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateWorkspaceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateWorkspaceRequest) GetCpu() int32 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

func (x *UpdateWorkspaceRequest) GetMemory() int32 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *UpdateWorkspaceRequest) GetStorage() int32 {
	if x != nil {
		return x.Storage
	}
	return 0
}

func (x *UpdateWorkspaceRequest) GetLanguages() []string {
	if x != nil {
		return x.Languages
	}
	return nil
}

func (x *UpdateWorkspaceRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

// DeleteWorkspaceRequest
type DeleteWorkspaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWorkspaceRequest) Reset() {
	*x = DeleteWorkspaceRequest{}
	mi := &file_workspace_workspace_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWorkspaceRequest) ProtoMessage() {}

func (x *DeleteWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_workspace_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*DeleteWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_workspace_workspace_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteWorkspaceRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// StartWorkspaceRequest
type StartWorkspaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartWorkspaceRequest) Reset() {
	*x = StartWorkspaceRequest{}
	mi := &file_workspace_workspace_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartWorkspaceRequest) ProtoMessage() {}

func (x *StartWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_workspace_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*StartWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_workspace_workspace_proto_rawDescGZIP(), []int{9}
}

func (x *StartWorkspaceRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// StopWorkspaceRequest
type StopWorkspaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopWorkspaceRequest) Reset() {
	*x = StopWorkspaceRequest{}
	mi := &file_workspace_workspace_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopWorkspaceRequest) ProtoMessage() {}

func (x *StopWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_workspace_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*StopWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_workspace_workspace_proto_rawDescGZIP(), []int{10}
}

func (x *StopWorkspaceRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// RestartWorkspaceRequest
type RestartWorkspaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartWorkspaceRequest) Reset() {
	*x = RestartWorkspaceRequest{}
	mi := &file_workspace_workspace_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartWorkspaceRequest) ProtoMessage() {}

func (x *RestartWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_workspace_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*RestartWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_workspace_workspace_proto_rawDescGZIP(), []int{11}
}

func (x *RestartWorkspaceRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// GetWorkspaceLogsRequest
type GetWorkspaceLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TailLines     int32                  `protobuf:"varint,2,opt,name=tail_lines,json=tailLines,proto3" json:"tail_lines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkspaceLogsRequest) Reset() {
	*x = GetWorkspaceLogsRequest{}
	mi := &file_workspace_workspace_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkspaceLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkspaceLogsRequest) ProtoMessage() {}

func (x *GetWorkspaceLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_workspace_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkspaceLogsRequest.ProtoReflect.Descriptor instead.
func (*GetWorkspaceLogsRequest) Descriptor() ([]byte, []int) {
	return file_workspace_workspace_proto_rawDescGZIP(), []int{12}
}

func (x *GetWorkspaceLogsRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetWorkspaceLogsRequest) GetTailLines() int32 {
	if x != nil {
		return x.TailLines
	}
	return 0
}

// WorkspaceLogsResponse
type WorkspaceLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          string                 `protobuf:"bytes,1,opt,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkspaceLogsResponse) Reset() {
	*x = WorkspaceLogsResponse{}
	mi := &file_workspace_workspace_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceLogsResponse) ProtoMessage() {}

func (x *WorkspaceLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_workspace_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceLogsResponse.ProtoReflect.Descriptor instead.
func (*WorkspaceLogsResponse) Descriptor() ([]byte, []int) {
	return file_workspace_workspace_proto_rawDescGZIP(), []int{13}
}

func (x *WorkspaceLogsResponse) GetLogs() string {
	if x != nil {
		return x.Logs
	}
	return ""
}

// InstallLanguageRequest
type InstallLanguageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   int32                  `protobuf:"varint,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Language      string                 `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallLanguageRequest) Reset() {
	*x = InstallLanguageRequest{}
	mi := &file_workspace_workspace_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallLanguageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallLanguageRequest) ProtoMessage() {}

func (x *InstallLanguageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_workspace_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallLanguageRequest.ProtoReflect.Descriptor instead.
func (*InstallLanguageRequest) Descriptor() ([]byte, []int) {
	return file_workspace_workspace_proto_rawDescGZIP(), []int{14}
}

func (x *InstallLanguageRequest) GetWorkspaceId() int32 {
	if x != nil {
		return x.WorkspaceId
	}
	return 0
}

func (x *InstallLanguageRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *InstallLanguageRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// InstallLanguageResponse
type InstallLanguageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Language      *Language              `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallLanguageResponse) Reset() {
	*x = InstallLanguageResponse{}
	mi := &file_workspace_workspace_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallLanguageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallLanguageResponse) ProtoMessage() {}

func (x *InstallLanguageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_workspace_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallLanguageResponse.ProtoReflect.Descriptor instead.
func (*InstallLanguageResponse) Descriptor() ([]byte, []int) {
	return file_workspace_workspace_proto_rawDescGZIP(), []int{15}
}

func (x *InstallLanguageResponse) GetLanguage() *Language {
	if x != nil {
		return x.Language
	}
	return nil
}

// ListLanguagesRequest
type ListLanguagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   int32                  `protobuf:"varint,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLanguagesRequest) Reset() {
	*x = ListLanguagesRequest{}
	mi := &file_workspace_workspace_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLanguagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLanguagesRequest) ProtoMessage() {}

func (x *ListLanguagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_workspace_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLanguagesRequest.ProtoReflect.Descriptor instead.
func (*ListLanguagesRequest) Descriptor() ([]byte, []int) {
	return file_workspace_workspace_proto_rawDescGZIP(), []int{16}
}

func (x *ListLanguagesRequest) GetWorkspaceId() int32 {
	if x != nil {
		return x.WorkspaceId
	}
	return 0
}

// ListLanguagesResponse
type ListLanguagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Languages     []*Language            `protobuf:"bytes,1,rep,name=languages,proto3" json:"languages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLanguagesResponse) Reset() {
	*x = ListLanguagesResponse{}
	mi := &file_workspace_workspace_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLanguagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLanguagesResponse) ProtoMessage() {}

func (x *ListLanguagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_workspace_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLanguagesResponse.ProtoReflect.Descriptor instead.
func (*ListLanguagesResponse) Descriptor() ([]byte, []int) {
	return file_workspace_workspace_proto_rawDescGZIP(), []int{17}
}

func (x *ListLanguagesResponse) GetLanguages() []*Language {
	if x != nil {
		return x.Languages
	}
	return nil
}

var File_workspace_workspace_proto protoreflect.FileDescriptor

const file_workspace_workspace_proto_rawDesc = "" +
	"\n" +
	"\x19workspace/workspace.proto\x12\rwws.workspace\x1a\x13common/common.proto\"\xf3\x04\n" +
	"\tWorkspace\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x10\n" +
	"\x03tag\x18\x02 \x01(\tR\x03tag\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12'\n" +
	"\x0forganization_id\x18\x04 \x01(\x05R\x0eorganizationId\x12\x19\n" +
	"\bowner_id\x18\x05 \x01(\x05R\aownerId\x12\x1a\n" +
	"\bprovider\x18\x06 \x01(\tR\bprovider\x12*\n" +
	"\x06status\x18\a \x01(\x0e2\x12.wws.common.StatusR\x06status\x12\x1a\n" +
	"\bendpoint\x18\b \x01(\tR\bendpoint\x12\x19\n" +
	"\bssh_host\x18\t \x01(\tR\asshHost\x12\x19\n" +
	"\bssh_port\x18\n" +
	" \x01(\x05R\asshPort\x12\x1b\n" +
	"\thttp_host\x18\v \x01(\tR\bhttpHost\x12\x1b\n" +
	"\thttp_port\x18\f \x01(\x05R\bhttpPort\x12\x1b\n" +
	"\tcode_host\x18\r \x01(\tR\bcodeHost\x12\x1b\n" +
	"\tcode_port\x18\x0e \x01(\x05R\bcodePort\x12\x10\n" +
	"\x03cpu\x18\x0f \x01(\x05R\x03cpu\x12\x16\n" +
	"\x06memory\x18\x10 \x01(\x05R\x06memory\x12\x18\n" +
	"\astorage\x18\x11 \x01(\x05R\astorage\x12\x16\n" +
	"\x06region\x18\x12 \x01(\tR\x06region\x12\x16\n" +
	"\x06config\x18\x13 \x01(\tR\x06config\x124\n" +
	"\n" +
	"created_at\x18\x14 \x01(\v2\x15.wws.common.TimestampR\tcreatedAt\x124\n" +
	"\n" +
	"updated_at\x18\x15 \x01(\v2\x15.wws.common.TimestampR\tupdatedAt\"\xcc\x01\n" +
	"\bLanguage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12!\n" +
	"\fworkspace_id\x18\x02 \x01(\x05R\vworkspaceId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12%\n" +
	"\x0einstall_script\x18\x05 \x01(\tR\rinstallScript\x128\n" +
	"\finstalled_at\x18\x06 \x01(\v2\x15.wws.common.TimestampR\vinstalledAt\"\x7f\n" +
	"\x15ListWorkspacesRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\x05R\x0eorganizationId\x12=\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1d.wws.common.PaginationRequestR\n" +
	"pagination\"\x92\x01\n" +
	"\x16ListWorkspacesResponse\x128\n" +
	"\n" +
	"workspaces\x18\x01 \x03(\v2\x18.wws.workspace.WorkspaceR\n" +
	"workspaces\x12>\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1e.wws.common.PaginationResponseR\n" +
	"pagination\"%\n" +
	"\x13GetWorkspaceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"K\n" +
	"\x11WorkspaceResponse\x126\n" +
	"\tworkspace\x18\x01 \x01(\v2\x18.wws.workspace.WorkspaceR\tworkspace\"\xcf\x01\n" +
	"\x16CreateWorkspaceRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\x05R\x0eorganizationId\x12\x10\n" +
	"\x03cpu\x18\x03 \x01(\x05R\x03cpu\x12\x16\n" +
	"\x06memory\x18\x04 \x01(\x05R\x06memory\x12\x18\n" +
	"\astorage\x18\x05 \x01(\x05R\astorage\x12\x1c\n" +
	"\tlanguages\x18\x06 \x03(\tR\tlanguages\x12\x16\n" +
	"\x06region\x18\a \x01(\tR\x06region\"\xb6\x01\n" +
	"\x16UpdateWorkspaceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03cpu\x18\x03 \x01(\x05R\x03cpu\x12\x16\n" +
	"\x06memory\x18\x04 \x01(\x05R\x06memory\x12\x18\n" +
	"\astorage\x18\x05 \x01(\x05R\astorage\x12\x1c\n" +
	"\tlanguages\x18\x06 \x03(\tR\tlanguages\x12\x16\n" +
	"\x06region\x18\a \x01(\tR\x06region\"(\n" +
	"\x16DeleteWorkspaceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"'\n" +
	"\x15StartWorkspaceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"&\n" +
	"\x14StopWorkspaceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\")\n" +
	"\x17RestartWorkspaceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"H\n" +
	"\x17GetWorkspaceLogsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1d\n" +
	"\n" +
	"tail_lines\x18\x02 \x01(\x05R\ttailLines\"+\n" +
	"\x15WorkspaceLogsResponse\x12\x12\n" +
	"\x04logs\x18\x01 \x01(\tR\x04logs\"q\n" +
	"\x16InstallLanguageRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\x05R\vworkspaceId\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"N\n" +
	"\x17InstallLanguageResponse\x123\n" +
	"\blanguage\x18\x01 \x01(\v2\x17.wws.workspace.LanguageR\blanguage\"9\n" +
	"\x14ListLanguagesRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\x05R\vworkspaceId\"N\n" +
	"\x15ListLanguagesResponse\x125\n" +
	"\tlanguages\x18\x01 \x03(\v2\x17.wws.workspace.LanguageR\tlanguages2\xfc\a\n" +
	"\x10WorkspaceService\x12]\n" +
	"\x0eListWorkspaces\x12$.wws.workspace.ListWorkspacesRequest\x1a%.wws.workspace.ListWorkspacesResponse\x12T\n" +
	"\fGetWorkspace\x12\".wws.workspace.GetWorkspaceRequest\x1a .wws.workspace.WorkspaceResponse\x12Z\n" +
	"\x0fCreateWorkspace\x12%.wws.workspace.CreateWorkspaceRequest\x1a .wws.workspace.WorkspaceResponse\x12Z\n" +
	"\x0fUpdateWorkspace\x12%.wws.workspace.UpdateWorkspaceRequest\x1a .wws.workspace.WorkspaceResponse\x12K\n" +
	"\x0fDeleteWorkspace\x12%.wws.workspace.DeleteWorkspaceRequest\x1a\x11.wws.common.Empty\x12X\n" +
	"\x0eStartWorkspace\x12$.wws.workspace.StartWorkspaceRequest\x1a .wws.workspace.WorkspaceResponse\x12V\n" +
	"\rStopWorkspace\x12#.wws.workspace.StopWorkspaceRequest\x1a .wws.workspace.WorkspaceResponse\x12\\\n" +
	"\x10RestartWorkspace\x12&.wws.workspace.RestartWorkspaceRequest\x1a .wws.workspace.WorkspaceResponse\x12`\n" +
	"\x10GetWorkspaceLogs\x12&.wws.workspace.GetWorkspaceLogsRequest\x1a$.wws.workspace.WorkspaceLogsResponse\x12`\n" +
	"\x0fInstallLanguage\x12%.wws.workspace.InstallLanguageRequest\x1a&.wws.workspace.InstallLanguageResponse\x12Z\n" +
	"\rListLanguages\x12#.wws.workspace.ListLanguagesRequest\x1a$.wws.workspace.ListLanguagesResponseB\x19Z\x17wws/api/proto/workspaceb\x06proto3"

var (
	file_workspace_workspace_proto_rawDescOnce sync.Once
	file_workspace_workspace_proto_rawDescData []byte
)

func file_workspace_workspace_proto_rawDescGZIP() []byte {
	file_workspace_workspace_proto_rawDescOnce.Do(func() {
		file_workspace_workspace_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workspace_workspace_proto_rawDesc), len(file_workspace_workspace_proto_rawDesc)))
	})
	return file_workspace_workspace_proto_rawDescData
}

var file_workspace_workspace_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_workspace_workspace_proto_goTypes = []any{
	(*Workspace)(nil),                 // 0: wws.workspace.Workspace
	(*Language)(nil),                  // 1: wws.workspace.Language
	(*ListWorkspacesRequest)(nil),     // 2: wws.workspace.ListWorkspacesRequest
	(*ListWorkspacesResponse)(nil),    // 3: wws.workspace.ListWorkspacesResponse
	(*GetWorkspaceRequest)(nil),       // 4: wws.workspace.GetWorkspaceRequest
	(*WorkspaceResponse)(nil),         // 5: wws.workspace.WorkspaceResponse
	(*CreateWorkspaceRequest)(nil),    // 6: wws.workspace.CreateWorkspaceRequest
	(*UpdateWorkspaceRequest)(nil),    // 7: wws.workspace.UpdateWorkspaceRequest
	(*DeleteWorkspaceRequest)(nil),    // 8: wws.workspace.DeleteWorkspaceRequest
	(*StartWorkspaceRequest)(nil),     // 9: wws.workspace.StartWorkspaceRequest
	(*StopWorkspaceRequest)(nil),      // 10: wws.workspace.StopWorkspaceRequest
	(*RestartWorkspaceRequest)(nil),   // 11: wws.workspace.RestartWorkspaceRequest
	(*GetWorkspaceLogsRequest)(nil),   // 12: wws.workspace.GetWorkspaceLogsRequest
	(*WorkspaceLogsResponse)(nil),     // 13: wws.workspace.WorkspaceLogsResponse
	(*InstallLanguageRequest)(nil),    // 14: wws.workspace.InstallLanguageRequest
	(*InstallLanguageResponse)(nil),   // 15: wws.workspace.InstallLanguageResponse
	(*ListLanguagesRequest)(nil),      // 16: wws.workspace.ListLanguagesRequest
	(*ListLanguagesResponse)(nil),     // 17: wws.workspace.ListLanguagesResponse
	(common.Status)(0),                // 18: wws.common.Status
	(*common.Timestamp)(nil),          // 19: wws.common.Timestamp
	(*common.PaginationRequest)(nil),  // 20: wws.common.PaginationRequest
	(*common.PaginationResponse)(nil), // 21: wws.common.PaginationResponse
	(*common.Empty)(nil),              // 22: wws.common.Empty
}
var file_workspace_workspace_proto_depIdxs = []int32{
	18, // 0: wws.workspace.Workspace.status:type_name -> wws.common.Status
	19, // 1: wws.workspace.Workspace.created_at:type_name -> wws.common.Timestamp
	19, // 2: wws.workspace.Workspace.updated_at:type_name -> wws.common.Timestamp
	19, // 3: wws.workspace.Language.installed_at:type_name -> wws.common.Timestamp
	20, // 4: wws.workspace.ListWorkspacesRequest.pagination:type_name -> wws.common.PaginationRequest
	0,  // 5: wws.workspace.ListWorkspacesResponse.workspaces:type_name -> wws.workspace.Workspace
	21, // 6: wws.workspace.ListWorkspacesResponse.pagination:type_name -> wws.common.PaginationResponse
	0,  // 7: wws.workspace.WorkspaceResponse.workspace:type_name -> wws.workspace.Workspace
	1,  // 8: wws.workspace.InstallLanguageResponse.language:type_name -> wws.workspace.Language
	1,  // 9: wws.workspace.ListLanguagesResponse.languages:type_name -> wws.workspace.Language
	2,  // 10: wws.workspace.WorkspaceService.ListWorkspaces:input_type -> wws.workspace.ListWorkspacesRequest
	4,  // 11: wws.workspace.WorkspaceService.GetWorkspace:input_type -> wws.workspace.GetWorkspaceRequest
	6,  // 12: wws.workspace.WorkspaceService.CreateWorkspace:input_type -> wws.workspace.CreateWorkspaceRequest
	7,  // 13: wws.workspace.WorkspaceService.UpdateWorkspace:input_type -> wws.workspace.UpdateWorkspaceRequest
	8,  // 14: wws.workspace.WorkspaceService.DeleteWorkspace:input_type -> wws.workspace.DeleteWorkspaceRequest
	9,  // 15: wws.workspace.WorkspaceService.StartWorkspace:input_type -> wws.workspace.StartWorkspaceRequest
	10, // 16: wws.workspace.WorkspaceService.StopWorkspace:input_type -> wws.workspace.StopWorkspaceRequest
	11, // 17: wws.workspace.WorkspaceService.RestartWorkspace:input_type -> wws.workspace.RestartWorkspaceRequest
	12, // 18: wws.workspace.WorkspaceService.GetWorkspaceLogs:input_type -> wws.workspace.GetWorkspaceLogsRequest
	14, // 19: wws.workspace.WorkspaceService.InstallLanguage:input_type -> wws.workspace.InstallLanguageRequest
	16, // 20: wws.workspace.WorkspaceService.ListLanguages:input_type -> wws.workspace.ListLanguagesRequest
	3,  // 21: wws.workspace.WorkspaceService.ListWorkspaces:output_type -> wws.workspace.ListWorkspacesResponse
	5,  // 22: wws.workspace.WorkspaceService.GetWorkspace:output_type -> wws.workspace.WorkspaceResponse
	5,  // 23: wws.workspace.WorkspaceService.CreateWorkspace:output_type -> wws.workspace.WorkspaceResponse
	5,  // 24: wws.workspace.WorkspaceService.UpdateWorkspace:output_type -> wws.workspace.WorkspaceResponse
	22, // 25: wws.workspace.WorkspaceService.DeleteWorkspace:output_type -> wws.common.Empty
	5,  // 26: wws.workspace.WorkspaceService.StartWorkspace:output_type -> wws.workspace.WorkspaceResponse
	5,  // 27: wws.workspace.WorkspaceService.StopWorkspace:output_type -> wws.workspace.WorkspaceResponse
	5,  // 28: wws.workspace.WorkspaceService.RestartWorkspace:output_type -> wws.workspace.WorkspaceResponse
	13, // 29: wws.workspace.WorkspaceService.GetWorkspaceLogs:output_type -> wws.workspace.WorkspaceLogsResponse
	15, // 30: wws.workspace.WorkspaceService.InstallLanguage:output_type -> wws.workspace.InstallLanguageResponse
	17, // 31: wws.workspace.WorkspaceService.ListLanguages:output_type -> wws.workspace.ListLanguagesResponse
	21, // [21:32] is the sub-list for method output_type
	10, // [10:21] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_workspace_workspace_proto_init() }
func file_workspace_workspace_proto_init() {
	if File_workspace_workspace_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workspace_workspace_proto_rawDesc), len(file_workspace_workspace_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_workspace_workspace_proto_goTypes,
		DependencyIndexes: file_workspace_workspace_proto_depIdxs,
		MessageInfos:      file_workspace_workspace_proto_msgTypes,
	}.Build()
	File_workspace_workspace_proto = out.File
	file_workspace_workspace_proto_goTypes = nil
	file_workspace_workspace_proto_depIdxs = nil
}
