run:
  timeout: 5m

linters:
  enable:
    - gofmt
    - govet
    - ineffassign
    - staticcheck
    - unused
  disable:
    - errcheck

linters-settings:
  govet:
    enable-all: true
    disable:
      - shadow
