FROM node:20-alpine AS builder

WORKDIR /build

COPY web/package.json ./
RUN npm install --legacy-peer-deps

COPY web/ ./
RUN npm run build

FROM nginx:alpine

COPY --from=builder /build/dist /usr/share/nginx/html
COPY web/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
